'use client';
import React,{useRef,useState} from 'react';
import Image from 'next/image';
import {AgentItem} from '@/types';
import {Mail,Phone,Plus,Upload,UserRound,X,Pencil,Trash2,Save} from 'lucide-react';
interface Props{agents:AgentItem[];onAgentsChange:(agents:AgentItem[])=>void}

// Practical DLD/marketplace-style Dubai community coverage. Keep labels human-friendly
// and deduplicated so agents can quickly select the areas they actually service.
const LOCATIONS=[
'Downtown Dubai','Business Bay','DIFC','Burj Khalifa District','Old Town','Opera District','Trade Centre 1','Trade Centre 2','World Trade Centre','One Central','Zabeel 1','Zabeel 2',
'Dubai Marina','Jumeirah Beach Residence (JBR)','The Walk JBR','Dubai Harbour','Emaar Beachfront','Bluewaters Island','Palm Jumeirah','Palm Jumeirah Fronds','Palm Jumeirah Crescent','Palm Jumeirah Trunk','Palm Jebel Ali','Dubai Islands','Deira Islands','Pearl Jumeirah','Jumeirah Bay Island','Port de La Mer','Madinat Jumeirah','Madinat Jumeirah Living','Burj Al Arab Area',
'Jumeirah','Jumeirah 1','Jumeirah 2','Jumeirah 3','Umm Suqeim','Umm Suqeim 1','Umm Suqeim 2','Umm Suqeim 3','Al Sufouh','Al Sufouh 1','Al Sufouh 2','Al Wasl','Al Safa','Al Safa 1','Al Safa 2','Al Badaa','Al Bada','Al Satwa','Al Hudaiba','Kite Beach','La Mer','City Walk','Dubai Water Canal',
'Al Barsha','Al Barsha 1','Al Barsha 2','Al Barsha 3','Al Barsha South','Al Barsha Heights (TECOM)','Barsha Heights','TECOM','Dubai Hills Estate','Dubai Science Park','Arjan','Al Sufouh','Dubai Internet City','Dubai Media City','Knowledge Village','Dubai Knowledge Park',
'Jumeirah Village Circle (JVC)','Jumeirah Village Triangle (JVT)','Jumeirah Park','Jumeirah Islands','Jumeirah Heights','Discovery Gardens','The Gardens','Ibn Battuta','Ibn Battuta Gate','Al Furjan','South Village','Jebel Ali','Jebel Ali Village','Jebel Ali Hills','Jebel Ali Free Zone (JAFZA)','Dubai Investment Park (DIP)','Green Community','Dubai Industrial City','Dubai Industrial Park',
'Meydan','Meydan City','Mohammed Bin Rashid City (MBR City)','District One','District 7','District 11','Sobha Hartland','Sobha Hartland II','Nad Al Sheba','Nad Al Sheba 1','Nad Al Sheba 2','Nad Al Sheba 3','Nad Al Sheba 4','Nad Al Shiba','Ras Al Khor','Ras Al Khor Industrial Area','Al Jaddaf','Al Jaddaf Waterfront','Culture Village','Dubai Creek','Dubai Creek Harbour','Dubai Festival City','Al Badia','Dubai Healthcare City','Dubai Design District (D3)','Dubai Design District','Dubai Maritime City','Mina Rashid','Port Rashid','Dubai Wharf',
'Mirdif','City Centre Mirdif','Muhaisnah','Muhaisnah 1','Muhaisnah 2','Muhaisnah 3','Muhaisnah 4','Al Warqa','Al Warqa 1','Al Warqa 2','Al Warqa 3','Al Warqa 4','Al Warqa 5','Al Twar','Al Twar 1','Al Twar 2','Al Twar 3','Al Qusais','Al Qusais 1','Al Qusais 2','Al Qusais 3','Al Qusais Industrial Area','Al Nahda Dubai','Al Mamzar','Al Khawaneej','Al Khawaneej 1','Al Khawaneej 2','Mizhar','Al Mizhar 1','Al Mizhar 2','Al Awir','Al Awir 1','Al Awir 2','Hatta',
'Deira','Al Rigga','Al Muteena','Naif','Hor Al Anz','Al Khabaisi','Al Baraha','Al Murar','Port Saeed','Al Garhoud','Dubai International Airport','Dubai Airport Freezone (DAFZA)','Dubai Airport Free Zone','Bur Dubai','Al Karama','Al Raffa','Al Mankhool','Oud Metha','Al Jafiliya',
'International City','Warsan','Warsan 1','Warsan 2','Warsan 3','Warsan 4','Warsan 5','Warsan 6','Warsan 7','Dubai Silicon Oasis','Silicon Oasis (DSO)','Academic City','Dubai International Academic City','Dubai Outsource City','Dubai CommerCity','Dubai Auto Zone','Dubai Production City (IMPZ)','Dubai Production City','Dubai Studio City','Dubai Sports City','Motor City','Dubai Autodrome',
'Dubailand','Dubai Land','Dubai Land Residence Complex (DLRC)','Dubai Residence Complex','Majan','Liwan','Queue Point','Skycourts Towers','Arjan','The Villa','The Villa Project','Mudon','Town Square','Remraam','The Sustainable City','Tilal Al Ghaf','Serena','Villanova','Haven by Aldar','The Valley','The Oasis','Cityland','Global Village','Living Legends','Falcon City of Wonders','Al Waha',
'Arabian Ranches','Arabian Ranches 1','Arabian Ranches 2','Arabian Ranches 3','Emirates Hills','Jumeirah Golf Estates','Victory Heights','Damac Hills','Damac Hills 2','DAMAC Hills 2','Damac Lagoons','Akoya Oxygen','Dubai South','Dubai World Central','Emaar South','Expo City Dubai','Dubai Maritime City','Dubai Waterfront','Waterfront','Riyadh City Dubai'
];

type Form={name:string;designation:string;phone:string;whatsApp:string;email:string;brn:string;reraBrokerId:string;specialization:string;bio:string;photo:string;languages:string;areas:string;status:'ACTIVE'|'INACTIVE'};
const blank=():Form=>({name:'',designation:'Senior Real Estate Advisor',phone:'',whatsApp:'',email:'',brn:'',reraBrokerId:'12048',specialization:'Luxury Residential',bio:'',photo:'',languages:'English, Arabic',areas:'Business Bay, Downtown Dubai',status:'ACTIVE'});

export const AgentsManagerEditable:React.FC<Props>=({agents,onAgentsChange})=>{
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<AgentItem|null>(null),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[locationOpen,setLocationOpen]=useState(false);
 const ref=useRef<HTMLInputElement>(null);const [form,setForm]=useState<Form>(blank());
 const set=(k:keyof Form,v:string)=>setForm(p=>({...p,[k]:v}));
 const selectedLocations=()=>form.areas.split(',').map(v=>v.trim()).filter(Boolean);
 const addLocation=(location:string)=>{const values=selectedLocations();if(values.includes(location))return;set('areas',[...values,location].join(', '));setLocationOpen(false)};
 const removeLocation=(location:string)=>set('areas',selectedLocations().filter(v=>v!==location).join(', '));
 const edit=(a:AgentItem)=>{setEditing(a);setForm({name:a.name||'',designation:a.designation||a.title||'Senior Real Estate Advisor',phone:a.phone||'',whatsApp:a.whatsApp||a.phone||'',email:a.email||'',brn:a.brn||'',reraBrokerId:a.reraBrokerId||'12048',specialization:a.specialization||'Luxury Residential',bio:a.bio||'',photo:a.photo||a.avatar||'',languages:(a.languages||[]).join(', '),areas:(a.areas||[]).join(', '),status:a.status||'ACTIVE'});setLocationOpen(false);setOpen(true)};
 const upload=async(file:File)=>{setUploading(true);try{const b=new FormData();b.append('file',file);const r=await fetch('/api/uploads',{method:'POST',body:b});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success||!j.data?.url)throw new Error(j.error||'Agent photo upload failed.');set('photo',j.data.url)}catch(e){alert(e instanceof Error?e.message:'Agent photo upload failed.')}finally{setUploading(false)}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!form.name.trim()||!form.email.trim()||!form.brn.trim()){alert('Name, email, and BRN are required.');return}setSaving(true);try{const p={name:form.name.trim(),photo:form.photo,avatar:form.photo,designation:form.designation.trim(),title:form.designation.trim(),phone:form.phone.trim(),whatsApp:form.whatsApp.trim()||form.phone.trim(),email:form.email.trim(),languages:form.languages.split(',').map(v=>v.trim()).filter(Boolean),nationality:'',specialization:form.specialization.trim(),areas:selectedLocations(),bio:form.bio.trim()||`${form.name.trim()} is a licensed Tanmiyat real estate advisor specialising in ${form.specialization.trim()}.`,reraBrokerId:form.reraBrokerId.trim()||'12048',brn:form.brn.trim(),licenseInformation:'',status:form.status,featured:editing?.featured??false};const r=await fetch(editing?`/api/agents/${editing.id}`:'/api/agents',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?p:{...p,slug:`${form.name.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${Date.now().toString().slice(-5)}`})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||'Agent save failed.');const a=j.data as AgentItem;onAgentsChange(editing?agents.map(x=>x.id===a.id?a:x):[a,...agents]);setOpen(false);setEditing(null);setForm(blank());setLocationOpen(false)}catch(e){alert(e instanceof Error?e.message:'Agent save failed.')}finally{setSaving(false)}};
 const remove=async(a:AgentItem)=>{if(!window.confirm(`Remove ${a.name} from active agents?\n\nExisting property records remain intact.`))return;try{const r=await fetch(`/api/agents/${a.id}`,{method:'DELETE'});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||'Agent removal failed.');onAgentsChange(agents.filter(x=>x.id!==a.id))}catch(e){alert(e instanceof Error?e.message:'Agent removal failed.')}};
 return <div className="space-y-4"><div className="flex items-center justify-between gap-3"><div><h2 className="font-editorial text-2xl text-[#F5F2EB]">Listing Agents & Advisors</h2><p className="text-[11px] text-[#8C867E]">Create, edit, replace photos, or remove advisors.</p></div><button type="button" onClick={()=>{setEditing(null);setForm(blank());setLocationOpen(false);setOpen(true)}} className="px-4 py-2.5 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold uppercase tracking-wider flex items-center gap-1.5"><Plus className="w-4 h-4"/>Add Agent</button></div>
 <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{agents.map(a=><div key={a.id} className="bg-[#171715] border border-[#25221E] p-4 flex gap-3"><div className="relative w-14 h-14 rounded-full overflow-hidden bg-[#0A0A09] border border-[#25221E] shrink-0">{a.photo||a.avatar?<Image src={a.photo||a.avatar||''} alt={a.name} fill className="object-cover" sizes="56px" referrerPolicy="no-referrer"/>:<div className="w-full h-full flex items-center justify-center text-[#B79A62]"><UserRound className="w-6 h-6"/></div>}</div><div className="min-w-0 flex-1"><div className="font-semibold text-[#F5F2EB] truncate">{a.name}</div><div className="text-[10px] text-[#B79A62]">{a.designation} • BRN {a.brn||'N/A'}</div><div className="text-[10px] text-[#8C867E] mt-1">{a.areas.join(', ')}</div><div className="flex gap-3 mt-2 text-[10px] text-[#A8A196] flex-wrap"><span className="inline-flex items-center gap-1"><Phone className="w-3 h-3"/>{a.phone}</span><span className="inline-flex items-center gap-1"><Mail className="w-3 h-3"/>{a.email}</span></div><div className="flex gap-2 mt-3"><button type="button" onClick={()=>edit(a)} className="px-2.5 py-1.5 border border-[#B79A62]/50 text-[#D8BE8A] text-[10px] uppercase tracking-wider inline-flex items-center gap-1"><Pencil className="w-3 h-3"/>Edit</button><button type="button" onClick={()=>void remove(a)} className="px-2.5 py-1.5 border border-red-900/60 text-red-300 text-[10px] uppercase tracking-wider inline-flex items-center gap-1"><Trash2 className="w-3 h-3"/>Delete</button></div></div></div>)}</div>
 {open&&<div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm"><div className="relative w-full max-w-3xl bg-[#171715] border border-[#25221E] p-6 sm:p-8 max-h-[92vh] overflow-y-auto"><div className="flex items-center justify-between pb-4 border-b border-[#25221E] mb-6"><div><h3 className="font-editorial text-2xl text-[#F5F2EB]">{editing?'Edit Agent / Advisor':'Add New Agent / Advisor'}</h3><p className="text-[11px] text-[#8C867E] mt-1">{editing?'Update details or replace the agent photo.':'This advisor becomes selectable on property listings.'}</p></div><button type="button" onClick={()=>{setOpen(false);setEditing(null);setLocationOpen(false)}}><X className="w-5 h-5 text-[#8C867E]"/></button></div><form onSubmit={save} className="space-y-4 text-xs"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Full Name *" value={form.name} onChange={v=>set('name',v)} required/><Field label="Email *" type="email" value={form.email} onChange={v=>set('email',v)} required/><Field label="Phone" value={form.phone} onChange={v=>set('phone',v)}/><Field label="WhatsApp" value={form.whatsApp} onChange={v=>set('whatsApp',v)}/><Field label="Agent BRN *" value={form.brn} onChange={v=>set('brn',v)} required/><Field label="Broker ORN" value={form.reraBrokerId} onChange={v=>set('reraBrokerId',v)}/></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Designation" value={form.designation} onChange={v=>set('designation',v)}/><Field label="Specialization" value={form.specialization} onChange={v=>set('specialization',v)}/>{editing&&<div><label className="block mb-1 text-[10px] uppercase tracking-wider text-[#8C867E]">Status</label><select value={form.status} onChange={e=>set('status',e.target.value)} className="w-full bg-[#0A0A09] border border-[#25221E] px-3 py-2 text-[#F5F2EB]"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>}</div>
 <div><label className="block mb-1 text-[10px] uppercase tracking-wider text-[#8C867E]">Agent Photo</label><input ref={ref} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value=''}}/><div className="flex items-center gap-3">{form.photo?<div className="relative w-16 h-16 rounded-full overflow-hidden border border-[#25221E]"><Image src={form.photo} alt="Agent preview" fill className="object-cover" sizes="64px" referrerPolicy="no-referrer"/></div>:<div className="w-16 h-16 rounded-full border border-[#25221E] flex items-center justify-center text-[#B79A62]"><UserRound className="w-6 h-6"/></div>}<button type="button" disabled={uploading} onClick={()=>ref.current?.click()} className="px-4 py-2.5 border border-dashed border-[#B79A62]/50 text-[#D8BE8A] flex items-center gap-2"><Upload className="w-4 h-4"/>{uploading?'Uploading photo...':editing?'Change Agent Photo':'Upload Agent Photo'}</button></div></div>
 <div className="relative"><label className="block mb-1.5 text-[10px] uppercase tracking-wider text-[#8C867E]">Specialized Locations</label><div className="min-h-10 rounded border border-[#25221E] bg-[#0A0A09] p-2 flex flex-wrap gap-1.5 mb-2">{selectedLocations().length?selectedLocations().map(location=><span key={location} className="inline-flex items-center gap-1 rounded bg-[#B79A62]/15 border border-[#B79A62]/40 px-2 py-1 text-[10px] text-[#D8BE8A]">{location}<button type="button" onClick={()=>removeLocation(location)} className="text-[#B79A62] hover:text-[#F5F2EB]" aria-label={`Remove ${location}`}><X className="w-3 h-3"/></button></span>):<span className="text-[10px] text-[#6F6A63] py-1">No specialized locations selected</span>}</div><button type="button" onClick={()=>setLocationOpen(v=>!v)} className="w-full flex items-center justify-between rounded border border-[#B79A62]/50 bg-[#0A0A09] px-3 py-2.5 text-left text-xs text-[#F5F2EB] hover:border-[#B79A62]"><span>{locationOpen?'Close location list':'Select specialized locations'}</span><span className="text-[#B79A62]">{selectedLocations().length} selected ▾</span></button>{locationOpen&&<div className="absolute left-0 right-0 top-full z-20 mt-1 max-h-72 overflow-y-auto rounded border border-[#B79A62]/50 bg-[#171715] shadow-2xl">{LOCATIONS.map(location=>{const selected=selectedLocations().includes(location);return <button type="button" key={location} disabled={selected} onClick={()=>addLocation(location)} className={`w-full flex items-center justify-between px-3 py-2 text-left text-[11px] border-b border-[#25221E] last:border-0 ${selected?'text-[#B79A62] bg-[#B79A62]/10 cursor-default':'text-[#D8D3CB] hover:bg-[#25221E] hover:text-[#F5F2EB]'}`}><span>{location}</span><span>{selected?'✓':'+'}</span></button>})}</div>}</div>
 <Field label="Languages (comma separated)" value={form.languages} onChange={v=>set('languages',v)}/><div><label className="block mb-1 text-[10px] uppercase tracking-wider text-[#8C867E]">Advisor Bio</label><textarea rows={4} value={form.bio} onChange={e=>set('bio',e.target.value)} className="w-full bg-[#0A0A09] border border-[#25221E] px-3 py-2 text-[#F5F2EB] outline-none focus:border-[#B79A62]"/></div><button type="submit" disabled={saving||uploading} className="w-full py-3.5 bg-[#B79A62] text-[#0A0A09] font-semibold uppercase tracking-wider disabled:opacity-50 inline-flex items-center justify-center gap-2"><Save className="w-4 h-4"/>{saving?(editing?'Saving Changes...':'Creating Agent...'):(editing?'Save Agent Changes':'Create Agent & Make Available to Listings')}</button></form></div></div>}
 </div>;
};
const Field=({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean})=><div><label className="block mb-1 text-[10px] uppercase tracking-wider text-[#8C867E]">{label}</label><input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full bg-[#0A0A09] border border-[#25221E] px-3 py-2 text-[#F5F2EB] outline-none focus:border-[#B79A62]"/></div>;
