'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { Building2, Layers3, Clock3, Newspaper, ShieldCheck, Plus, Save, X } from 'lucide-react';
import type { ProjectItem, UnitItem, TimelineItem, NewsItem } from '@/types';

type Props = { projects: ProjectItem[]; units: UnitItem[]; timeline: TimelineItem[]; news: NewsItem[]; onRefresh: () => Promise<void> };
type Section = 'PROJECTS' | 'UNITS' | 'TIMELINE' | 'NEWS' | 'USERS';
const card='bg-[#171715] border border-[#25221E]';
const input='w-full bg-[#0A0A09] border border-[#2D2A26] px-3 py-2.5 text-sm text-[#F5F2EB] focus:outline-none focus:border-[#B79A62]';

export const DevelopmentCMSManager: React.FC<Props> = ({ projects, units, timeline, news, onRefresh }) => {
 const [section,setSection]=useState<Section>('PROJECTS'); const [projectOpen,setProjectOpen]=useState(false); const [newsOpen,setNewsOpen]=useState(false); const [saving,setSaving]=useState(false); const [localUnits,setLocalUnits]=useState<UnitItem[]>(units);
 const [projectForm,setProjectForm]=useState({title:'',titleAr:'',category:'RESIDENTIAL',status:'UPCOMING',location:'Dubai, UAE',locationAr:'دبي، الإمارات العربية المتحدة',tagline:'',taglineAr:'',overview:'',overviewAr:'',architecture:'',architectureAr:'',heroImage:'',startingPrice:'',completionDate:''});
 const [newsForm,setNewsForm]=useState({title:'',titleAr:'',excerpt:'',excerptAr:'',content:'',contentAr:'',featuredImage:'',author:'Tanmiyat Editorial',category:'Insights'});
 useEffect(()=>{let active=true;const hydrate=async()=>{const result=await Promise.all(projects.map(async p=>{try{const r=await fetch(`/api/projects/${p.id}`,{cache:'no-store'});const j=await r.json().catch(()=>({}));return r.ok&&j.success&&Array.isArray(j.data?.units)?j.data.units as UnitItem[]:[]}catch{return []}}));if(active)setLocalUnits(result.flat())};void hydrate();return()=>{active=false}},[projects]);
 const projectMap=useMemo(()=>new Map(projects.map(p=>[p.id,p.title])),[projects]);
 const post=async(url:string,body:unknown)=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||`Request failed (${r.status})`);return j.data;};
 const saveProject=async()=>{if(!projectForm.title.trim()){alert('Project title is required.');return}setSaving(true);try{const slug=projectForm.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-6);await post('/api/projects',{...projectForm,slug,startingPrice:projectForm.startingPrice?Number(projectForm.startingPrice):undefined,currency:'AED',isFeatured:false,order:projects.length+1,amenities:[],gallery:[],documents:[],heroImage:projectForm.heroImage||'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80'});setProjectOpen(false);setProjectForm({title:'',titleAr:'',category:'RESIDENTIAL',status:'UPCOMING',location:'Dubai, UAE',locationAr:'دبي، الإمارات العربية المتحدة',tagline:'',taglineAr:'',overview:'',overviewAr:'',architecture:'',architectureAr:'',heroImage:'',startingPrice:'',completionDate:''});await onRefresh()}catch(e){alert(e instanceof Error?e.message:'Project creation failed')}finally{setSaving(false)}};
 const saveNews=async()=>{if(!newsForm.title.trim()||!newsForm.content.trim()){alert('News title and content are required.');return}setSaving(true);try{const slug=newsForm.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-6);await post('/api/news',{...newsForm,slug,publishedDate:new Date().toISOString(),isPublished:true,seoTitle:newsForm.title,seoDescription:newsForm.excerpt});setNewsOpen(false);setNewsForm({title:'',titleAr:'',excerpt:'',excerptAr:'',content:'',contentAr:'',featuredImage:'',author:'Tanmiyat Editorial',category:'Insights'});await onRefresh()}catch(e){alert(e instanceof Error?e.message:'News creation failed')}finally{setSaving(false)}};
 const tabs:[Section,string,React.ElementType,number][]=[['PROJECTS','Master Projects',Building2,projects.length],['UNITS','Inventory Units',Layers3,localUnits.length],['TIMELINE','Heritage Timeline',Clock3,timeline.length],['NEWS','News & Insights',Newspaper,news.length],['USERS','Roles & Access',ShieldCheck,1]];
 return <div className="space-y-6"><div><h1 className="font-editorial text-3xl text-[#F5F2EB]">Development & CMS</h1><p className="text-xs text-[#8C867E] mt-1">Developments, inventory, heritage content, editorial publishing and access policy.</p></div><div className="grid grid-cols-2 lg:grid-cols-5 gap-2">{tabs.map(([id,label,Icon,count])=><button key={id} onClick={()=>setSection(id)} className={`${card} p-3 text-left transition-colors ${section===id?'border-[#B79A62] bg-[#1C1A17]':''}`}><Icon className="w-5 h-5 text-[#B79A62] mb-2"/><div className="text-[10px] uppercase tracking-wider text-[#C8C0B3]">{label}</div><div className="text-xl text-[#F5F2EB] mt-1">{count}</div></button>)}</div>
 {section==='PROJECTS'&&<Panel title="Master Projects" action={<button onClick={()=>setProjectOpen(true)} className="px-4 py-2 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold"><Plus className="inline w-4 h-4 mr-1"/>New Project</button>}><div className="grid md:grid-cols-2 gap-4">{projects.map(p=><div key={p.id} className={`${card} p-5`}><div className="flex justify-between gap-3"><div><h3 className="text-lg text-[#F5F2EB]">{p.title}</h3><p className="text-[10px] text-[#B79A62] uppercase tracking-wider">{p.category} • {p.status}</p></div><span className="text-[10px] text-[#8C867E]">#{p.order}</span></div><p className="text-xs text-[#8C867E] mt-3">{p.location}</p><p className="text-xs text-[#C8C0B3] mt-2 line-clamp-3">{p.tagline}</p><div className="mt-4 text-[10px] text-[#7A756D]">{(p.units||[]).length} linked units • {p.gallery.length} gallery items • {p.amenities.length} amenities</div></div>)}</div>{!projects.length&&<Empty text="No master projects found."/>}</Panel>}
 {section==='UNITS'&&<Panel title="Inventory Units"><div className={`${card} overflow-x-auto`}><table className="w-full text-xs"><thead className="bg-[#0A0A09] text-[#7A756D]"><tr><th className="p-3 text-left">Unit</th><th className="p-3 text-left">Project</th><th className="p-3 text-left">Type</th><th className="p-3 text-left">Beds</th><th className="p-3 text-left">Area</th><th className="p-3 text-left">Price</th><th className="p-3 text-left">Status</th></tr></thead><tbody className="divide-y divide-[#22201C]">{localUnits.map(u=><tr key={u.id}><td className="p-3 text-[#F5F2EB]">{u.unitNumber}</td><td className="p-3">{projectMap.get(u.projectId)||'Unlinked'}</td><td className="p-3">{u.type}</td><td className="p-3">{u.bedrooms}</td><td className="p-3">{u.areaSqFt.toLocaleString()} sq ft</td><td className="p-3">AED {u.price.toLocaleString()}</td><td className="p-3"><span className="px-2 py-1 border border-[#25221E] text-[10px]">{u.status}</span></td></tr>)}</tbody></table>{!localUnits.length&&<Empty text="No inventory units are currently indexed."/>}</div><p className="text-[10px] text-[#7A756D]">Units are hydrated from the existing project detail API so the CMS does not invent a new data source.</p></Panel>}
 {section==='TIMELINE'&&<Panel title="Heritage Timeline"><div className="space-y-3">{timeline.map(t=><div key={t.id} className={`${card} p-5 flex gap-5`}><div className="text-2xl text-[#B79A62] font-editorial w-20 shrink-0">{t.year}</div><div><h3 className="text-[#F5F2EB]">{t.title}</h3><p className="text-xs text-[#8C867E] mt-1">{t.description}</p></div></div>)}{!timeline.length&&<Empty text="No heritage timeline records found."/>}</div></Panel>}
 {section==='NEWS'&&<Panel title="News & Insights" action={<button onClick={()=>setNewsOpen(true)} className="px-4 py-2 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold"><Plus className="inline w-4 h-4 mr-1"/>New Article</button>}><div className="grid md:grid-cols-2 gap-4">{news.map(n=><div key={n.id} className={`${card} p-5`}><div className="text-[10px] uppercase tracking-wider text-[#B79A62]">{n.category} • {n.isPublished?'PUBLISHED':'DRAFT'}</div><h3 className="text-lg text-[#F5F2EB] mt-2">{n.title}</h3><p className="text-xs text-[#8C867E] mt-2 line-clamp-3">{n.excerpt}</p><div className="text-[10px] text-[#7A756D] mt-4">{n.author} • {new Date(n.publishedDate).toLocaleDateString()}</div></div>)}{!news.length&&<Empty text="No news articles found."/>}</div></Panel>}
 {section==='USERS'&&<Panel title="Roles & Access"><div className={`${card} p-5`}><div className="flex items-center gap-3"><ShieldCheck className="w-6 h-6 text-[#B79A62]"/><div><div className="text-[#F5F2EB] font-semibold">SUPER_ADMIN</div><div className="text-xs text-[#8C867E]">Current executive account</div></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-5">{['SUPER_ADMIN','ADMIN','SALES_MANAGER','AGENT','MARKETING','CRM_MANAGER','ACCOUNTANT','VIEWER','EDITOR','SALES'].map(role=><div key={role} className="border border-[#25221E] bg-[#0A0A09] px-3 py-2 text-[10px] text-[#C8C0B3]">{role}</div>)}</div><p className="text-xs text-[#8C867E] mt-5">The current backend uses the configured administrator account and SUPER_ADMIN JWT. Multi-user credential provisioning is not exposed until the backend has a persistent user store.</p></div></Panel>}
 {projectOpen&&<Modal title="Create Master Project" close={()=>!saving&&setProjectOpen(false)}><div className="grid md:grid-cols-2 gap-4">{[['Title','title'],['Arabic Title','titleAr'],['Location','location'],['Arabic Location','locationAr'],['Tagline','tagline'],['Arabic Tagline','taglineAr'],['Hero Image URL','heroImage'],['Starting Price AED','startingPrice'],['Completion Date','completionDate']].map(([label,key])=><Field key={key} label={label} value={(projectForm as Record<string,string>)[key]} type={key==='startingPrice'?'number':'text'} onChange={v=>setProjectForm(p=>({...p,[key]:v}))}/>)}<Select label="Category" value={projectForm.category} options={['RESIDENTIAL','COMMERCIAL','MIXED_USE','MASTER_COMMUNITY']} onChange={v=>setProjectForm(p=>({...p,category:v}))}/><Select label="Status" value={projectForm.status} options={['COMPLETED','ONGOING','UPCOMING']} onChange={v=>setProjectForm(p=>({...p,status:v}))}/></div><TextArea label="Overview" value={projectForm.overview} onChange={v=>setProjectForm(p=>({...p,overview:v}))}/><TextArea label="Architecture" value={projectForm.architecture} onChange={v=>setProjectForm(p=>({...p,architecture:v}))}/><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setProjectOpen(false)} className="px-4 py-2 border border-[#332F28]">Cancel</button><button onClick={()=>void saveProject()} disabled={saving} className="px-5 py-2 bg-[#B79A62] text-[#0A0A09] font-semibold"><Save className="inline w-4 h-4 mr-1"/>{saving?'Saving...':'Create Project'}</button></div></Modal>}
 {newsOpen&&<Modal title="Publish News & Insight" close={()=>!saving&&setNewsOpen(false)}><div className="grid md:grid-cols-2 gap-4"><Field label="Title" value={newsForm.title} onChange={v=>setNewsForm(p=>({...p,title:v}))}/><Field label="Arabic Title" value={newsForm.titleAr} onChange={v=>setNewsForm(p=>({...p,titleAr:v}))}/><Field label="Featured Image URL" value={newsForm.featuredImage} onChange={v=>setNewsForm(p=>({...p,featuredImage:v}))}/><Field label="Category" value={newsForm.category} onChange={v=>setNewsForm(p=>({...p,category:v}))}/><Field label="Author" value={newsForm.author} onChange={v=>setNewsForm(p=>({...p,author:v}))}/></div><TextArea label="Excerpt" value={newsForm.excerpt} onChange={v=>setNewsForm(p=>({...p,excerpt:v}))}/><TextArea label="Content" value={newsForm.content} onChange={v=>setNewsForm(p=>({...p,content:v}))}/><TextArea label="Arabic Content" value={newsForm.contentAr} onChange={v=>setNewsForm(p=>({...p,contentAr:v}))}/><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setNewsOpen(false)} className="px-4 py-2 border border-[#332F28]">Cancel</button><button onClick={()=>void saveNews()} disabled={saving} className="px-5 py-2 bg-[#B79A62] text-[#0A0A09] font-semibold"><Save className="inline w-4 h-4 mr-1"/>{saving?'Publishing...':'Publish Article'}</button></div></Modal>}
 </div>;
};
const Panel=({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode})=><section className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 className="font-editorial text-2xl text-[#F5F2EB]">{title}</h2>{action}</div>{children}</section>;
const Empty=({text}:{text:string})=><div className="p-8 text-center text-xs text-[#7A756D]">{text}</div>;
const Field=({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string})=><label className="block"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><input className={input} type={type} value={value||''} onChange={e=>onChange(e.target.value)}/></label>;
const TextArea=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className="block mt-4"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><textarea rows={5} className={input} value={value||''} onChange={e=>onChange(e.target.value)}/></label>;
const Select=({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void})=><label className="block"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><select className={input} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>;
const Modal=({title,close,children}:{title:string;close:()=>void;children:React.ReactNode})=><div className="fixed inset-0 z-[80] bg-black/80 flex items-center justify-center p-4"><div className="w-full max-w-4xl max-h-[92vh] overflow-y-auto bg-[#171715] border border-[#25221E] p-6 sm:p-8"><div className="flex justify-between items-center mb-6"><h3 className="font-editorial text-2xl text-[#F5F2EB]">{title}</h3><button onClick={close}><X className="w-5 h-5 text-[#8C867E]"/></button></div>{children}</div></div>;
