'use client';

import React, { useMemo, useState } from 'react';
import { Building2, Layers3, Clock3, Newspaper, ShieldCheck, Plus, Pencil, Trash2, Upload, Save, X, Search, FileText, Image as ImageIcon } from 'lucide-react';
import type { ProjectItem, UnitItem, TimelineItem, NewsItem } from '@/types';

type Props={projects:ProjectItem[];units:UnitItem[];timeline:TimelineItem[];news:NewsItem[];onRefresh:()=>Promise<void>};
type Section='PROJECTS'|'UNITS'|'TIMELINE'|'NEWS'|'USERS';
const card='bg-[#171715] border border-[#25221E]';
const input='w-full bg-[#0A0A09] border border-[#2D2A26] px-3 py-2.5 text-sm text-[#F5F2EB] focus:outline-none focus:border-[#B79A62]';
const emptyProject=()=>({title:'',titleAr:'',category:'RESIDENTIAL',status:'UPCOMING',location:'Dubai, UAE',locationAr:'دبي، الإمارات العربية المتحدة',tagline:'',taglineAr:'',overview:'',overviewAr:'',architecture:'',architectureAr:'',heroImage:'',startingPrice:'',completionDate:'',isFeatured:false,order:0,amenities:[],gallery:[],documents:[],currency:'AED'} as any);
const emptyUnit=()=>({projectId:'',unitNumber:'',type:'APARTMENT',bedrooms:0,bathrooms:0,areaSqFt:0,floor:'',price:0,currency:'AED',status:'AVAILABLE',floorPlanUrl:'',images:[]} as any);
const emptyTimeline=()=>({year:new Date().getFullYear(),title:'',titleAr:'',description:'',descriptionAr:'',imageUrl:''});
const emptyNews=()=>({title:'',titleAr:'',slug:'',excerpt:'',excerptAr:'',content:'',contentAr:'',featuredImage:'',author:'Tanmiyat Editorial',category:'Insights',publishedDate:new Date().toISOString(),isPublished:false,seoTitle:'',seoDescription:''});

export const DevelopmentCMSManagerV2:React.FC<Props>=({projects,units,timeline,news,onRefresh})=>{
 const [section,setSection]=useState<Section>('PROJECTS'); const [search,setSearch]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 const [project,setProject]=useState<any>(null); const [unit,setUnit]=useState<any>(null); const [time,setTime]=useState<any>(null); const [article,setArticle]=useState<any>(null);
 const projectMap=useMemo(()=>new Map(projects.map(p=>[p.id,p.title])),[projects]);
 const filteredProjects=projects.filter(p=>`${p.title} ${p.location} ${p.category}`.toLowerCase().includes(search.toLowerCase()));
 const filteredUnits=units.filter(u=>`${u.unitNumber} ${projectMap.get(u.projectId)||''} ${u.type}`.toLowerCase().includes(search.toLowerCase()));
 const filteredTimeline=timeline.filter(t=>`${t.year} ${t.title} ${t.description}`.toLowerCase().includes(search.toLowerCase()));
 const filteredNews=news.filter(n=>`${n.title} ${n.category} ${n.author}`.toLowerCase().includes(search.toLowerCase()));
 const api=async(url:string,method='GET',body?:unknown)=>{const r=await fetch(url,{method,credentials:'include',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||`Request failed (${r.status})`);return j.data;};
 const save=async()=>{setBusy(true);setNotice('');try{if(project){const body={...project,startingPrice:project.startingPrice===''?undefined:Number(project.startingPrice),order:Number(project.order||0)};if(project.id)await api(`/api/projects/${project.id}`,'PATCH',body);else await api('/api/projects','POST',{...body,slug:(project.slug||project.title).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-6)});setProject(null)}else if(unit){if(unit.id)await api(`/api/units/${unit.id}`,'PATCH',{...unit,bedrooms:Number(unit.bedrooms),bathrooms:Number(unit.bathrooms),areaSqFt:Number(unit.areaSqFt),price:Number(unit.price),floor:unit.floor===''?undefined:Number(unit.floor)});else await api('/api/units','POST',{...unit,bedrooms:Number(unit.bedrooms),bathrooms:Number(unit.bathrooms),areaSqFt:Number(unit.areaSqFt),price:Number(unit.price),floor:unit.floor===''?undefined:Number(unit.floor)});setUnit(null)}else if(time){if(time.id)await api(`/api/timeline/${time.id}`,'PATCH',time);else {setNotice('New timeline entries require the persistent timeline repository migration; existing entries can be edited safely.');return}setTime(null)}else if(article){const slug=(article.slug||article.title).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`article-${Date.now()}`;const body={...article,slug,publishedDate:article.publishedDate||new Date().toISOString(),seoTitle:article.seoTitle||article.title,seoDescription:article.seoDescription||article.excerpt};if(article.id)await api(`/api/news/${article.id}`,'PATCH',body);else await api('/api/news','POST',body);setArticle(null)}await onRefresh();setNotice('Changes saved successfully.')}catch(e){setNotice(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}};
 const remove=async(kind:string,id:string)=>{if(!window.confirm(`Are you sure you want to delete/archive this ${kind}? This action is recorded in the audit log.`))return;setBusy(true);try{const url=kind==='project'?`/api/projects/${id}`:kind==='unit'?`/api/units/${id}`:kind==='timeline'?`/api/timeline/${id}`:`/api/news/${id}`;await api(url,'DELETE');await onRefresh();setNotice(`${kind} removed successfully.`)}catch(e){setNotice(e instanceof Error?e.message:'Delete failed.')}finally{setBusy(false)}};
 const upload=async(file:File)=>{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/uploads',{method:'POST',credentials:'include',body:fd});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||'Upload failed');return j.data?.url||j.data?.files?.[0]?.url||''};
 const UploadField=({label,onDone,accept}:{label:string;onDone:(url:string)=>void;accept?:string})=><label className="flex items-center gap-2 px-3 py-2.5 border border-dashed border-[#403B33] bg-[#0A0A09] text-xs text-[#C8C0B3] cursor-pointer hover:border-[#B79A62]"><Upload className="w-4 h-4 text-[#B79A62]"/>{label}<input className="hidden" type="file" accept={accept} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{setBusy(true);onDone(await upload(f));setNotice('Upload complete.');}catch(err){setNotice(err instanceof Error?err.message:'Upload failed.')}finally{setBusy(false)}}}/></label>;
 const tabs:[Section,string,any,number][]=[['PROJECTS','Master Projects',Building2,projects.length],['UNITS','Inventory Units',Layers3,units.length],['TIMELINE','Heritage Timeline',Clock3,timeline.length],['NEWS','News & Insights',Newspaper,news.length],['USERS','Roles & Access',ShieldCheck,1]];
 return <div className="space-y-6"><div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-editorial text-3xl text-[#F5F2EB]">Development & CMS</h1><p className="text-xs text-[#8C867E] mt-1">Professional content, inventory and development administration.</p></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-3 w-4 h-4 text-[#7A756D]"/><input className={`${input} pl-9`} placeholder="Search this section..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div></div><div className="grid grid-cols-2 lg:grid-cols-5 gap-2">{tabs.map(([id,label,Icon,count])=><button key={id} onClick={()=>{setSection(id);setSearch('')}} className={`${card} p-3 text-left ${section===id?'border-[#B79A62] bg-[#1C1A17]':''}`}><Icon className="w-5 h-5 text-[#B79A62] mb-2"/><div className="text-[10px] uppercase tracking-wider text-[#C8C0B3]">{label}</div><div className="text-xl text-[#F5F2EB] mt-1">{count}</div></button>)}</div>{notice&&<div className="px-4 py-3 border border-[#403B33] bg-[#121210] text-xs text-[#D8BE8A]">{notice}</div>}
 {section==='PROJECTS'&&<Panel title="Master Projects" action={<button onClick={()=>setProject(emptyProject())} className="btn"><Plus/>New Project</button>}><div className="grid md:grid-cols-2 gap-4">{filteredProjects.map(p=><div key={p.id} className={`${card} p-5`}><div className="flex gap-4"><div className="w-24 h-20 bg-[#0A0A09] shrink-0 overflow-hidden">{p.heroImage?<img src={p.heroImage} className="w-full h-full object-cover" alt=""/>:<ImageIcon className="m-auto mt-7 text-[#5E5A54]"/>}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><h3 className="text-lg text-[#F5F2EB] truncate">{p.title}</h3><span className="text-[10px] text-[#B79A62]">#{p.order}</span></div><p className="text-[10px] text-[#B79A62] uppercase tracking-wider">{p.category} • {p.status}</p><p className="text-xs text-[#8C867E] mt-2">{p.location}</p></div></div><div className="mt-4 text-[10px] text-[#7A756D]">{p.gallery?.length||0} gallery • {p.documents?.length||0} documents • {p.amenities?.length||0} amenities</div><Actions edit={()=>setProject({...p,startingPrice:p.startingPrice??'',completionDate:p.completionDate??''})} del={()=>void remove('project',p.id)}/></div>)}</div>{!filteredProjects.length&&<Empty text="No projects match this search."/>}</Panel>}
 {section==='UNITS'&&<Panel title="Inventory Units" action={<button onClick={()=>setUnit(emptyUnit())} className="btn"><Plus/>New Unit</button>}><div className={`${card} overflow-x-auto`}><table className="w-full text-xs"><thead className="bg-[#0A0A09] text-[#7A756D]"><tr><th className="p-3 text-left">Unit</th><th className="p-3 text-left">Project</th><th className="p-3 text-left">Type</th><th className="p-3 text-left">Beds</th><th className="p-3 text-left">Area</th><th className="p-3 text-left">Price</th><th className="p-3">Actions</th></tr></thead><tbody className="divide-y divide-[#22201C]">{filteredUnits.map(u=><tr key={u.id}><td className="p-3 text-[#F5F2EB]">{u.unitNumber}</td><td className="p-3">{projectMap.get(u.projectId)||'Unlinked'}</td><td className="p-3">{u.type}</td><td className="p-3">{u.bedrooms}</td><td className="p-3">{Number(u.areaSqFt).toLocaleString()} sq ft</td><td className="p-3">AED {Number(u.price).toLocaleString()}</td><td className="p-3"><div className="flex justify-end gap-1"><IconButton title="Edit" onClick={()=>setUnit({...u})}><Pencil/></IconButton><IconButton title="Delete" onClick={()=>void remove('unit',u.id)} danger><Trash2/></IconButton></div></td></tr>)}</tbody></table>{!filteredUnits.length&&<Empty text="No inventory units match this search."/>}</div></Panel>}
 {section==='TIMELINE'&&<Panel title="Heritage Timeline"><div className="space-y-3">{filteredTimeline.map(t=><div key={t.id} className={`${card} p-5 flex gap-5 items-start`}><div className="text-2xl text-[#B79A62] font-editorial w-20 shrink-0">{t.year}</div><div className="flex-1"><h3 className="text-[#F5F2EB]">{t.title}</h3><p className="text-xs text-[#8C867E] mt-1">{t.description}</p><div className="flex gap-2 mt-4"><button className="mini" onClick={()=>setTime({...t})}><Pencil/>Edit</button><button className="mini danger" onClick={()=>void remove('timeline',t.id)}><Trash2/>Delete</button></div></div>{t.imageUrl&&<img src={t.imageUrl} alt="" className="w-24 h-20 object-cover"/>}</div>)}{!filteredTimeline.length&&<Empty text="No timeline records match this search."/>}</div></Panel>}
 {section==='NEWS'&&<Panel title="News & Insights" action={<button onClick={()=>setArticle(emptyNews())} className="btn"><Plus/>New Article</button>}><div className="grid md:grid-cols-2 gap-4">{filteredNews.map(n=><div key={n.id} className={`${card} p-5`}><div className="flex gap-4">{n.featuredImage&&<img src={n.featuredImage} alt="" className="w-24 h-20 object-cover shrink-0"/>}<div className="min-w-0"><div className="text-[10px] uppercase tracking-wider text-[#B79A62]">{n.category} • {n.isPublished?'PUBLISHED':'DRAFT'}</div><h3 className="text-lg text-[#F5F2EB] mt-2">{n.title}</h3><p className="text-xs text-[#8C867E] mt-2 line-clamp-3">{n.excerpt}</p></div></div><Actions edit={()=>setArticle({...n})} del={()=>void remove('news',n.id)}/></div>)}</div>{!filteredNews.length&&<Empty text="No articles match this search."/>}</Panel>}
 {section==='USERS'&&<Panel title="Roles & Access"><div className={`${card} p-5`}><div className="flex items-center gap-3"><ShieldCheck className="w-6 h-6 text-[#B79A62]"/><div><div className="text-[#F5F2EB] font-semibold">SUPER_ADMIN</div><div className="text-xs text-[#8C867E]">Current executive account</div></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-5">{['SUPER_ADMIN','ADMIN','SALES_MANAGER','AGENT','MARKETING','CRM_MANAGER','ACCOUNTANT','VIEWER','EDITOR','SALES'].map(role=><div key={role} className="border border-[#25221E] bg-[#0A0A09] px-3 py-2 text-[10px] text-[#C8C0B3]">{role}</div>)}</div><p className="text-xs text-[#8C867E] mt-5">Credential provisioning remains protected by the existing backend authentication model; no fake user accounts are created here.</p></div></Panel>}
 {project&&<Editor title={project.id?'Edit Master Project':'Create Master Project'} close={()=>setProject(null)} save={save} busy={busy}><div className="grid md:grid-cols-2 gap-4">{[['Title','title'],['Arabic Title','titleAr'],['Location','location'],['Arabic Location','locationAr'],['Tagline','tagline'],['Arabic Tagline','taglineAr'],['Starting Price AED','startingPrice'],['Completion Date','completionDate']].map(([l,k])=><Field key={k} label={l} value={project[k]??''} onChange={v=>setProject({...project,[k]:v})}/>) }<Select label="Category" value={project.category} options={['RESIDENTIAL','COMMERCIAL','MIXED_USE','MASTER_COMMUNITY']} onChange={v=>setProject({...project,category:v})}/><Select label="Status" value={project.status} options={['COMPLETED','ONGOING','UPCOMING']} onChange={v=>setProject({...project,status:v})}/></div><TextArea label="Overview" value={project.overview} onChange={v=>setProject({...project,overview:v})}/><TextArea label="Architecture" value={project.architecture} onChange={v=>setProject({...project,architecture:v})}/><div className="grid md:grid-cols-2 gap-3 mt-4"><UploadField label="Upload hero image" accept="image/*" onDone={url=>setProject({...project,heroImage:url})}/><UploadField label="Upload brochure / document" accept="application/pdf,.doc,.docx" onDone={url=>setProject({...project,brochureUrl:url})}/></div><div className="mt-4 p-4 border border-[#25221E] bg-[#0A0A09]"><div className="text-[10px] uppercase tracking-wider text-[#B79A62] mb-3">Gallery</div><UploadField label="Upload gallery image" accept="image/*" onDone={url=>setProject({...project,gallery:[...(project.gallery||[]),{id:`gallery-${Date.now()}`,imageUrl:url}]})}/><div className="flex flex-wrap gap-2 mt-3">{(project.gallery||[]).map((g:any)=><div key={g.id} className="relative w-20 h-16"><img src={g.imageUrl} alt="" className="w-full h-full object-cover"/><button type="button" onClick={()=>setProject({...project,gallery:(project.gallery||[]).filter((x:any)=>x.id!==g.id)})} className="absolute -top-2 -right-2 rounded-full bg-black p-1"><X className="w-3 h-3"/></button></div>)}</div></div></Editor>}
 {unit&&<Editor title={unit.id?'Edit Inventory Unit':'Create Inventory Unit'} close={()=>setUnit(null)} save={save} busy={busy}><div className="grid md:grid-cols-2 gap-4"><Select label="Project" value={unit.projectId} options={projects.map(p=>p.id)} labels={new Map(projects.map(p=>[p.id,p.title]))} onChange={v=>setUnit({...unit,projectId:v})}/>{[['Unit Number','unitNumber'],['Type','type'],['Bedrooms','bedrooms'],['Bathrooms','bathrooms'],['Area Sq Ft','areaSqFt'],['Floor','floor'],['Price AED','price']].map(([l,k])=><Field key={k} label={l} value={unit[k]??''} type={['bedrooms','bathrooms','areaSqFt','floor','price'].includes(k)?'number':'text'} onChange={v=>setUnit({...unit,[k]:v})}/>) }<Select label="Status" value={unit.status} options={['AVAILABLE','RESERVED','SOLD','BLOCKED']} onChange={v=>setUnit({...unit,status:v})}/></div><div className="grid md:grid-cols-2 gap-3 mt-4"><UploadField label="Upload floor plan" accept="image/*,application/pdf" onDone={url=>setUnit({...unit,floorPlanUrl:url})}/><UploadField label="Upload unit image" accept="image/*" onDone={url=>setUnit({...unit,images:[...(unit.images||[]),url]})}/></div></Editor>}
 {time&&<Editor title="Edit Heritage Timeline" close={()=>setTime(null)} save={save} busy={busy}><div className="grid md:grid-cols-2 gap-4"><Field label="Year" value={time.year} type="number" onChange={v=>setTime({...time,year:Number(v)})}/><Field label="Title" value={time.title} onChange={v=>setTime({...time,title:v})}/><Field label="Arabic Title" value={time.titleAr} onChange={v=>setTime({...time,titleAr:v})}/></div><TextArea label="Description" value={time.description} onChange={v=>setTime({...time,description:v})}/><TextArea label="Arabic Description" value={time.descriptionAr} onChange={v=>setTime({...time,descriptionAr:v})}/><UploadField label="Upload timeline image" accept="image/*" onDone={url=>setTime({...time,imageUrl:url})}/></Editor>}
 {article&&<Editor title={article.id?'Edit Article':'Create Article'} close={()=>setArticle(null)} save={save} busy={busy}><div className="grid md:grid-cols-2 gap-4">{[['Title','title'],['Arabic Title','titleAr'],['Category','category'],['Author','author'],['SEO Title','seoTitle'],['SEO Description','seoDescription']].map(([l,k])=><Field key={k} label={l} value={article[k]??''} onChange={v=>setArticle({...article,[k]:v})}/>)}</div><TextArea label="Excerpt" value={article.excerpt} onChange={v=>setArticle({...article,excerpt:v})}/><TextArea label="Arabic Excerpt" value={article.excerptAr} onChange={v=>setArticle({...article,excerptAr:v})}/><TextArea label="Content" value={article.content} onChange={v=>setArticle({...article,content:v})}/><TextArea label="Arabic Content" value={article.contentAr} onChange={v=>setArticle({...article,contentAr:v})}/><div className="grid md:grid-cols-2 gap-3 mt-4"><UploadField label="Upload featured image" accept="image/*" onDone={url=>setArticle({...article,featuredImage:url})}/><label className="flex items-center gap-3 border border-[#25221E] px-3 py-2.5 text-xs"><input type="checkbox" checked={Boolean(article.isPublished)} onChange={e=>setArticle({...article,isPublished:e.target.checked})}/>Published</label></div></Editor>}
 </div>;
};
const Panel=({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode})=><section className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 className="font-editorial text-2xl text-[#F5F2EB]">{title}</h2>{action}</div>{children}</section>;
const Empty=({text}:{text:string})=><div className="p-8 text-center text-xs text-[#7A756D]">{text}</div>;
const Field=({label,value,onChange,type='text'}:{label:string;value:any;onChange:(v:any)=>void;type?:string})=><label className="block"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><input className={input} type={type} value={value??''} onChange={e=>onChange(e.target.value)}/></label>;
const TextArea=({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void})=><label className="block mt-4"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><textarea rows={5} className={input} value={value??''} onChange={e=>onChange(e.target.value)}/></label>;
const Select=({label,value,options,onChange,labels}:{label:string;value:string;options:string[];onChange:(v:string)=>void;labels?:Map<string,string>})=><label className="block"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><select className={input} value={value||''} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{labels?.get(o)||o}</option>)}</select></label>;
const Actions=({edit,del}:{edit:()=>void;del:()=>void})=><div className="flex justify-end gap-1 mt-4"><IconButton title="Edit" onClick={edit}><Pencil/></IconButton><IconButton title="Delete" onClick={del} danger><Trash2/></IconButton></div>;
const IconButton=({title,onClick,children,danger}:{title:string;onClick:()=>void;children:React.ReactNode;danger?:boolean})=><button type="button" title={title} onClick={onClick} className={`p-2 border border-[#302D28] ${danger?'hover:text-red-400':'hover:text-[#B79A62]'}`}>{React.cloneElement(children as React.ReactElement,{className:'w-4 h-4'})}</button>;
const Editor=({title,close,save,busy,children}:{title:string;close:()=>void;save:()=>void;busy:boolean;children:React.ReactNode})=><div className="fixed inset-0 z-50 bg-black/75 p-4 sm:p-8 overflow-y-auto"><div className="max-w-4xl mx-auto bg-[#171715] border border-[#332F28] shadow-2xl"><div className="sticky top-0 z-10 bg-[#171715] border-b border-[#25221E] px-5 py-4 flex items-center justify-between"><h2 className="font-editorial text-2xl text-[#F5F2EB]">{title}</h2><button onClick={close} disabled={busy}><X className="w-5 h-5"/></button></div><div className="p-5 sm:p-7">{children}<div className="flex justify-end gap-2 mt-7 pt-5 border-t border-[#25221E]"><button onClick={close} disabled={busy} className="px-4 py-2 border border-[#332F28] text-xs">Cancel</button><button onClick={save} disabled={busy} className="px-5 py-2 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold"><Save className="inline w-4 h-4 mr-1"/>{busy?'Saving...':'Save Changes'}</button></div></div></div></div>;
const UploadField=({label,onDone,accept}:{label:string;onDone:(url:string)=>void;accept?:string})=><label className="flex items-center gap-2 px-3 py-2.5 border border-dashed border-[#403B33] bg-[#0A0A09] text-xs text-[#C8C0B3] cursor-pointer"><Upload className="w-4 h-4 text-[#B79A62]"/>{label}<input className="hidden" type="file" accept={accept} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{const r=await fetch('/api/uploads',{method:'POST',credentials:'include',body:fd});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Upload failed');onDone(j.data?.url||j.data?.files?.[0]?.url||'')}catch(err){alert(err instanceof Error?err.message:'Upload failed')}}}/></label>;
const btn='inline-flex items-center gap-1.5 px-4 py-2 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold';
