'use client';

import React, { useMemo, useState } from 'react';
import { Building2, Layers3, Clock3, Newspaper, ShieldCheck, Plus, Pencil, Trash2, Upload, Save, X, Search, Image as ImageIcon } from 'lucide-react';
import type { ProjectItem, UnitItem, TimelineItem, NewsItem } from '@/types';

type Props={projects:ProjectItem[];units:UnitItem[];timeline:TimelineItem[];news:NewsItem[];onRefresh:()=>Promise<void>};
type Section='PROJECTS'|'UNITS'|'TIMELINE'|'NEWS'|'USERS';
const input='w-full bg-[#0A0A09] border border-[#2D2A26] px-3 py-2.5 text-sm text-[#F5F2EB] focus:outline-none focus:border-[#B79A62]';
const card='bg-[#171715] border border-[#25221E]';
const projectBlank=()=>({title:'',titleAr:'',category:'RESIDENTIAL',status:'UPCOMING',location:'Dubai, UAE',locationAr:'دبي، الإمارات العربية المتحدة',tagline:'',taglineAr:'',overview:'',overviewAr:'',architecture:'',architectureAr:'',heroImage:'',startingPrice:'',completionDate:'',isFeatured:false,order:0,amenities:[],gallery:[],documents:[],currency:'AED'} as any);
const unitBlank=()=>({projectId:'',unitNumber:'',type:'APARTMENT',bedrooms:0,bathrooms:0,areaSqFt:0,floor:'',price:0,currency:'AED',status:'AVAILABLE',floorPlanUrl:'',images:[]} as any);
const newsBlank=()=>({title:'',titleAr:'',slug:'',excerpt:'',excerptAr:'',content:'',contentAr:'',featuredImage:'',author:'Tanmiyat Editorial',category:'Insights',publishedDate:new Date().toISOString(),isPublished:false,seoTitle:'',seoDescription:''});

export const DevelopmentCMSManagerV2:React.FC<Props>=({projects,units,timeline,news,onRefresh})=>{
 const [section,setSection]=useState<Section>('PROJECTS'); const [search,setSearch]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 const [editing,setEditing]=useState<any>(null); const [kind,setKind]=useState<'project'|'unit'|'timeline'|'news'|null>(null);
 const projectMap=useMemo(()=>new Map(projects.map(p=>[p.id,p.title])),[projects]);
 const list=section==='PROJECTS'?projects.filter(p=>`${p.title} ${p.location} ${p.category}`.toLowerCase().includes(search.toLowerCase())):section==='UNITS'?units.filter(u=>`${u.unitNumber} ${projectMap.get(u.projectId)||''} ${u.type}`.toLowerCase().includes(search.toLowerCase())):section==='TIMELINE'?timeline.filter(t=>`${t.year} ${t.title} ${t.description}`.toLowerCase().includes(search.toLowerCase())):news.filter(n=>`${n.title} ${n.category} ${n.author}`.toLowerCase().includes(search.toLowerCase()));
 const api=async(url:string,method='GET',body?:unknown)=>{const r=await fetch(url,{method,credentials:'include',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||`Request failed (${r.status})`);return j.data;};
 const upload=async(file:File)=>{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/uploads',{method:'POST',credentials:'include',body:fd});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||'Upload failed');return j.data?.url||j.data?.files?.[0]?.url||''};
 const save=async()=>{if(!editing||!kind)return;setBusy(true);setNotice('');try{if(kind==='project'){const body={...editing,startingPrice:editing.startingPrice===''?undefined:Number(editing.startingPrice),order:Number(editing.order||0)};if(editing.id)await api(`/api/projects/${editing.id}`,'PATCH',body);else await api('/api/projects','POST',{...body,slug:(editing.slug||editing.title).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-6)});}else if(kind==='unit'){const body={...editing,bedrooms:Number(editing.bedrooms),bathrooms:Number(editing.bathrooms),areaSqFt:Number(editing.areaSqFt),price:Number(editing.price),floor:editing.floor===''?undefined:Number(editing.floor)};await api(editing.id?`/api/units/${editing.id}`:'/api/units',editing.id?'PATCH':'POST',body);}else if(kind==='timeline'){await api(`/api/timeline/${editing.id}`,'PATCH',editing);}else{const body={...editing,slug:(editing.slug||editing.title).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`article-${Date.now()}`,publishedDate:editing.publishedDate||new Date().toISOString(),seoTitle:editing.seoTitle||editing.title,seoDescription:editing.seoDescription||editing.excerpt};await api(editing.id?`/api/news/${editing.id}`:'/api/news',editing.id?'PATCH':'POST',body);}setEditing(null);setKind(null);await onRefresh();setNotice('Changes saved successfully.');}catch(e){setNotice(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}};
 const remove=async(k:string,id:string)=>{if(!window.confirm(`Are you sure you want to delete/archive this ${k}?`))return;setBusy(true);try{await api(k==='project'?`/api/projects/${id}`:k==='unit'?`/api/units/${id}`:k==='timeline'?`/api/timeline/${id}`:`/api/news/${id}`,'DELETE');await onRefresh();setNotice(`${k} removed successfully.`)}catch(e){setNotice(e instanceof Error?e.message:'Delete failed.')}finally{setBusy(false)}};
 const begin=(k:any,value:any)=>{setKind(k);setEditing(value)};
 const tabs:[Section,string,any,number][]=[['PROJECTS','Master Projects',Building2,projects.length],['UNITS','Inventory Units',Layers3,units.length],['TIMELINE','Heritage Timeline',Clock3,timeline.length],['NEWS','News & Insights',Newspaper,news.length],['USERS','Roles & Access',ShieldCheck,1]];
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-editorial text-3xl text-[#F5F2EB]">Development & CMS</h1><p className="text-xs text-[#8C867E] mt-1">Professional development content, inventory and publishing administration.</p></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-3 w-4 h-4 text-[#7A756D]"/><input className={`${input} pl-9`} placeholder="Search this section..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="grid grid-cols-2 lg:grid-cols-5 gap-2">{tabs.map(([id,label,Icon,count])=><button key={id} onClick={()=>{setSection(id);setSearch('')}} className={`${card} p-3 text-left ${section===id?'border-[#B79A62] bg-[#1C1A17]':''}`}><Icon className="w-5 h-5 text-[#B79A62] mb-2"/><div className="text-[10px] uppercase tracking-wider text-[#C8C0B3]">{label}</div><div className="text-xl text-[#F5F2EB]">{count}</div></button>)}</div>{notice&&<div className="border border-[#403B33] bg-[#121210] px-4 py-3 text-xs text-[#D8BE8A]">{notice}</div>}
 {section==='PROJECTS'&&<Panel title="Master Projects" action={<button className={btn} onClick={()=>begin('project',projectBlank())}><Plus/>New Project</button>}><div className="grid md:grid-cols-2 gap-4">{list.map((p:any)=><Card key={p.id} title={p.title} meta={`${p.category} • ${p.status}`} detail={p.location} image={p.heroImage} footer={`${p.gallery?.length||0} gallery • ${p.documents?.length||0} documents • ${p.amenities?.length||0} amenities`} edit={()=>begin('project',{...p,startingPrice:p.startingPrice??'',completionDate:p.completionDate??''})} del={()=>remove('project',p.id)}/>)}</div>{!list.length&&<Empty/>}</Panel>}
 {section==='UNITS'&&<Panel title="Inventory Units" action={<button className={btn} onClick={()=>begin('unit',unitBlank())}><Plus/>New Unit</button>}><div className={`${card} overflow-x-auto`}><table className="w-full text-xs"><thead className="bg-[#0A0A09] text-[#7A756D]"><tr>{['Unit','Project','Type','Beds','Area','Price','Actions'].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody className="divide-y divide-[#22201C]">{list.map((u:any)=><tr key={u.id}><td className="p-3 text-[#F5F2EB]">{u.unitNumber}</td><td className="p-3">{projectMap.get(u.projectId)||'Unlinked'}</td><td className="p-3">{u.type}</td><td className="p-3">{u.bedrooms}</td><td className="p-3">{Number(u.areaSqFt).toLocaleString()} sq ft</td><td className="p-3">AED {Number(u.price).toLocaleString()}</td><td className="p-3"><Actions edit={()=>begin('unit',{...u})} del={()=>remove('unit',u.id)}/></td></tr>)}</tbody></table>{!list.length&&<Empty/>}</div></Panel>}
 {section==='TIMELINE'&&<Panel title="Heritage Timeline" action={<button className={btn} onClick={()=>setNotice('Timeline creation is intentionally disabled until a repository-backed create method is added; existing entries remain fully editable/deletable.')}> <Plus/>New Entry</button>}><div className="space-y-3">{list.map((t:any)=><div key={t.id} className={`${card} p-5 flex gap-4 items-start`}><div className="text-2xl text-[#B79A62] font-editorial w-20">{t.year}</div><div className="flex-1"><h3 className="text-[#F5F2EB]">{t.title}</h3><p className="text-xs text-[#8C867E] mt-1">{t.description}</p><Actions edit={()=>begin('timeline',{...t})} del={()=>remove('timeline',t.id)}/></div>{t.imageUrl&&<img src={t.imageUrl} alt="" className="w-24 h-20 object-cover"/>}</div>)}</div></Panel>}
 {section==='NEWS'&&<Panel title="News & Insights" action={<button className={btn} onClick={()=>begin('news',newsBlank())}><Plus/>New Article</button>}><div className="grid md:grid-cols-2 gap-4">{list.map((n:any)=><Card key={n.id} title={n.title} meta={`${n.category} • ${n.isPublished?'PUBLISHED':'DRAFT'}`} detail={n.excerpt} image={n.featuredImage} edit={()=>begin('news',{...n})} del={()=>remove('news',n.id)}/>)}</div>{!list.length&&<Empty/>}</Panel>}
 {section==='USERS'&&<Panel title="Roles & Access"><div className={`${card} p-5`}><div className="flex items-center gap-3"><ShieldCheck className="w-6 h-6 text-[#B79A62]"/><div><div className="text-[#F5F2EB] font-semibold">SUPER_ADMIN</div><div className="text-xs text-[#8C867E]">Current executive account</div></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-5">{['SUPER_ADMIN','ADMIN','SALES_MANAGER','AGENT','MARKETING','CRM_MANAGER','ACCOUNTANT','VIEWER','EDITOR','SALES'].map(r=><div key={r} className="border border-[#25221E] bg-[#0A0A09] px-3 py-2 text-[10px] text-[#C8C0B3]">{r}</div>)}</div></div></Panel>}
 {editing&&<Editor title={`${editing.id?'Edit ':'Create '}${kind}`} close={()=>{setEditing(null);setKind(null)}} save={save} busy={busy}>{kind==='project'&&<><div className="grid md:grid-cols-2 gap-4">{[['Title','title'],['Arabic Title','titleAr'],['Location','location'],['Arabic Location','locationAr'],['Tagline','tagline'],['Arabic Tagline','taglineAr'],['Starting Price','startingPrice'],['Completion Date','completionDate']].map(([l,k])=><Field key={k} label={l} value={editing[k]??''} onChange={v=>setEditing({...editing,[k]:v})}/>)}</div><Text label="Overview" value={editing.overview} onChange={v=>setEditing({...editing,overview:v})}/><Text label="Architecture" value={editing.architecture} onChange={v=>setEditing({...editing,architecture:v})}/><div className="grid md:grid-cols-2 gap-3 mt-4"><UploadField label="Upload hero image" accept="image/*" onDone={url=>setEditing({...editing,heroImage:url})}/><UploadField label="Upload brochure / document" accept="application/pdf,.doc,.docx" onDone={url=>setEditing({...editing,brochureUrl:url})}/></div><div className="mt-4 p-4 border border-[#25221E]"><div className="text-[10px] uppercase text-[#B79A62] mb-3">Gallery</div><UploadField label="Upload gallery image" accept="image/*" onDone={url=>setEditing({...editing,gallery:[...(editing.gallery||[]),{id:`gallery-${Date.now()}`,imageUrl:url}]})}/><div className="flex flex-wrap gap-2 mt-3">{(editing.gallery||[]).map((g:any)=><div key={g.id} className="relative w-20 h-16"><img src={g.imageUrl} alt="" className="w-full h-full object-cover"/><button type="button" onClick={()=>setEditing({...editing,gallery:editing.gallery.filter((x:any)=>x.id!==g.id)})} className="absolute -top-2 -right-2 rounded-full bg-black p-1"><X className="w-3 h-3"/></button></div>)}</div></div></>}
 {kind==='unit'&&<><div className="grid md:grid-cols-2 gap-4"><Select label="Project" value={editing.projectId} options={projects.map(p=>p.id)} labels={projectMap} onChange={v=>setEditing({...editing,projectId:v})}/>{[['Unit Number','unitNumber'],['Type','type'],['Bedrooms','bedrooms'],['Bathrooms','bathrooms'],['Area Sq Ft','areaSqFt'],['Floor','floor'],['Price AED','price']].map(([l,k])=><Field key={k} label={l} value={editing[k]??''} type={['bedrooms','bathrooms','areaSqFt','floor','price'].includes(k)?'number':'text'} onChange={v=>setEditing({...editing,[k]:v})}/>) }<Select label="Status" value={editing.status} options={['AVAILABLE','RESERVED','SOLD','BLOCKED']} onChange={v=>setEditing({...editing,status:v})}/></div><div className="grid md:grid-cols-2 gap-3 mt-4"><UploadField label="Upload floor plan" accept="image/*,application/pdf" onDone={url=>setEditing({...editing,floorPlanUrl:url})}/><UploadField label="Upload unit image" accept="image/*" onDone={url=>setEditing({...editing,images:[...(editing.images||[]),url]})}/></div></>}
 {kind==='timeline'&&<><div className="grid md:grid-cols-2 gap-4"><Field label="Year" value={editing.year} type="number" onChange={v=>setEditing({...editing,year:Number(v)})}/><Field label="Title" value={editing.title} onChange={v=>setEditing({...editing,title:v})}/><Field label="Arabic Title" value={editing.titleAr} onChange={v=>setEditing({...editing,titleAr:v})}/></div><Text label="Description" value={editing.description} onChange={v=>setEditing({...editing,description:v})}/><Text label="Arabic Description" value={editing.descriptionAr} onChange={v=>setEditing({...editing,descriptionAr:v})}/><UploadField label="Upload timeline image" accept="image/*" onDone={url=>setEditing({...editing,imageUrl:url})}/></>}
 {kind==='news'&&<><div className="grid md:grid-cols-2 gap-4">{[['Title','title'],['Arabic Title','titleAr'],['Category','category'],['Author','author'],['SEO Title','seoTitle'],['SEO Description','seoDescription']].map(([l,k])=><Field key={k} label={l} value={editing[k]??''} onChange={v=>setEditing({...editing,[k]:v})}/>)}</div><Text label="Excerpt" value={editing.excerpt} onChange={v=>setEditing({...editing,excerpt:v})}/><Text label="Arabic Excerpt" value={editing.excerptAr} onChange={v=>setEditing({...editing,excerptAr:v})}/><Text label="Content" value={editing.content} onChange={v=>setEditing({...editing,content:v})}/><Text label="Arabic Content" value={editing.contentAr} onChange={v=>setEditing({...editing,contentAr:v})}/><div className="grid md:grid-cols-2 gap-3 mt-4"><UploadField label="Upload featured image" accept="image/*" onDone={url=>setEditing({...editing,featuredImage:url})}/><label className="flex items-center gap-3 border border-[#25221E] px-3 py-2.5 text-xs"><input type="checkbox" checked={Boolean(editing.isPublished)} onChange={e=>setEditing({...editing,isPublished:e.target.checked})}/>Published</label></div></>}
 </Editor>}</div>;
};
const Panel=({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode})=><section className="space-y-4"><div className="flex items-center justify-between"><h2 className="font-editorial text-2xl text-[#F5F2EB]">{title}</h2>{action}</div>{children}</section>;
const Empty=()=> <div className="p-8 text-center text-xs text-[#7A756D]">No records found.</div>;
const Field=({label,value,onChange,type='text'}:{label:string;value:any;onChange:(v:any)=>void;type?:string})=><label className="block"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><input className={input} type={type} value={value??''} onChange={e=>onChange(e.target.value)}/></label>;
const Text=({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void})=><label className="block mt-4"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><textarea rows={5} className={input} value={value??''} onChange={e=>onChange(e.target.value)}/></label>;
const Select=({label,value,options,onChange,labels}:{label:string;value:string;options:string[];onChange:(v:string)=>void;labels?:Map<string,string>})=><label className="block"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><select className={input} value={value||''} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{labels?.get(o)||o}</option>)}</select></label>;
const UploadField=({label,onDone,accept}:{label:string;onDone:(url:string)=>void;accept?:string})=><label className="flex items-center gap-2 px-3 py-2.5 border border-dashed border-[#403B33] bg-[#0A0A09] text-xs text-[#C8C0B3] cursor-pointer"><Upload className="w-4 h-4 text-[#B79A62]"/>{label}<input className="hidden" type="file" accept={accept} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{const r=await fetch('/api/uploads',{method:'POST',credentials:'include',body:fd});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Upload failed');onDone(j.data?.url||j.data?.files?.[0]?.url||'')}catch(err){alert(err instanceof Error?err.message:'Upload failed')}}}/></label>;
const Actions=({edit,del}:{edit:()=>void;del:()=>void})=><div className="flex justify-end gap-1 mt-3"><button type="button" title="Edit" onClick={edit} className="p-2 border border-[#302D28] hover:text-[#B79A62]"><Pencil className="w-4 h-4"/></button><button type="button" title="Delete" onClick={del} className="p-2 border border-[#302D28] hover:text-red-400"><Trash2 className="w-4 h-4"/></button></div>;
const Card=({title,meta,detail,image,footer,edit,del}:{title:string;meta:string;detail:string;image?:string;footer?:string;edit:()=>void;del:()=>void})=><div className={`${card} p-5`}><div className="flex gap-4"><div className="w-24 h-20 shrink-0 bg-[#0A0A09] overflow-hidden">{image?<img src={image} alt="" className="w-full h-full object-cover"/>:<ImageIcon className="m-auto mt-7 text-[#5E5A54]"/>}</div><div className="min-w-0 flex-1"><h3 className="text-lg text-[#F5F2EB] truncate">{title}</h3><p className="text-[10px] uppercase tracking-wider text-[#B79A62]">{meta}</p><p className="text-xs text-[#8C867E] mt-2 line-clamp-3">{detail}</p></div></div>{footer&&<div className="text-[10px] text-[#7A756D] mt-4">{footer}</div>}<Actions edit={edit} del={del}/></div>;
const Editor=({title,close,save,busy,children}:{title:string;close:()=>void;save:()=>void;busy:boolean;children:React.ReactNode})=><div className="fixed inset-0 z-50 bg-black/75 p-4 sm:p-8 overflow-y-auto"><div className="max-w-4xl mx-auto bg-[#171715] border border-[#332F28] shadow-2xl"><div className="sticky top-0 z-10 bg-[#171715] border-b border-[#25221E] px-5 py-4 flex justify-between"><h2 className="font-editorial text-2xl text-[#F5F2EB]">{title}</h2><button onClick={close} disabled={busy}><X/></button></div><div className="p-5 sm:p-7">{children}<div className="flex justify-end gap-2 mt-7 pt-5 border-t border-[#25221E]"><button onClick={close} disabled={busy} className="px-4 py-2 border border-[#332F28] text-xs">Cancel</button><button onClick={save} disabled={busy} className={btn}><Save className="w-4 h-4"/>{busy?'Saving...':'Save Changes'}</button></div></div></div></div>;
const btn='inline-flex items-center gap-1.5 px-4 py-2 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold';
