'use client';

import React, { useMemo, useState } from 'react';
import { Building2, Layers3, Clock3, Newspaper, ShieldCheck, Plus, Save, X, RefreshCw } from 'lucide-react';
import type { ProjectItem, UnitItem, TimelineItem, NewsItem } from '@/types';

type Props = { projects: ProjectItem[]; units: UnitItem[]; timeline: TimelineItem[]; news: NewsItem[]; onRefresh: () => Promise<void> };
type Section = 'PROJECTS' | 'UNITS' | 'TIMELINE' | 'NEWS' | 'USERS';

const card='bg-[#171715] border border-[#25221E]';
const input='w-full bg-[#0A0A09] border border-[#2D2A26] px-3 py-2.5 text-sm text-[#F5F2EB] focus:outline-none focus:border-[#B79A62]';

export const DevelopmentCMSManager: React.FC<Props> = ({ projects, units, timeline, news, onRefresh }) => {
  const [section,setSection]=useState<Section>('PROJECTS');
  const [showProject,setShowProject]=useState(false);
  const [showUnit,setShowUnit]=useState(false);
  const [showNews,setShowNews]=useState(false);
  const [saving,setSaving]=useState(false);
  const [projectForm,setProjectForm]=useState({title:'',titleAr:'',category:'RESIDENTIAL',status:'UPCOMING',location:'Dubai, UAE',locationAr:'دبي، الإمارات العربية المتحدة',tagline:'',taglineAr:'',overview:'',overviewAr:'',architecture:'',architectureAr:'',heroImage:'',startingPrice:'',completionDate:''});
  const [unitForm,setUnitForm]=useState({projectId:'',unitNumber:'',type:'Apartment',bedrooms:'2',bathrooms:'2',areaSqFt:'',floor:'',price:'',status:'AVAILABLE'});
  const [newsForm,setNewsForm]=useState({title:'',titleAr:'',excerpt:'',excerptAr:'',content:'',contentAr:'',featuredImage:'',author:'Tanmiyat Editorial',category:'Insights'});

  const projectMap=useMemo(()=>new Map(projects.map(p=>[p.id,p.title])),[projects]);
  const post=async(url:string,body:unknown)=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||`Request failed (${r.status})`);return j.data;};
  const saveProject=async()=>{if(!projectForm.title.trim()){alert('Project title is required.');return}setSaving(true);try{const slug=projectForm.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-6);await post('/api/projects',{...projectForm,slug,startingPrice:projectForm.startingPrice?Number(projectForm.startingPrice):undefined,currency:'AED',isFeatured:false,order:projects.length+1,amenities:[],gallery:[],documents:[],heroImage:projectForm.heroImage||'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80'});setShowProject(false);setProjectForm({title:'',titleAr:'',category:'RESIDENTIAL',status:'UPCOMING',location:'Dubai, UAE',locationAr:'دبي، الإمارات العربية المتحدة',tagline:'',taglineAr:'',overview:'',overviewAr:'',architecture:'',architectureAr:'',heroImage:'',startingPrice:'',completionDate:''});await onRefresh();}catch(e){alert(e instanceof Error?e.message:'Project creation failed')}finally{setSaving(false)}};
  const saveUnit=async()=>{if(!unitForm.projectId||!unitForm.unitNumber||!unitForm.areaSqFt||!unitForm.price){alert('Project, unit number, area and price are required.');return}setSaving(true);try{await post('/api/units',{projectId:unitForm.projectId,unitNumber:unitForm.unitNumber,type:unitForm.type,bedrooms:Number(unitForm.bedrooms)||0,bathrooms:Number(unitForm.bathrooms)||0,areaSqFt:Number(unitForm.areaSqFt),floor:unitForm.floor?Number(unitForm.floor):undefined,price:Number(unitForm.price),currency:'AED',status:unitForm.status,images:[]});setShowUnit(false);setUnitForm({projectId:'',unitNumber:'',type:'Apartment',bedrooms:'2',bathrooms:'2',areaSqFt:'',floor:'',price:'',status:'AVAILABLE'});await onRefresh();}catch(e){alert(e instanceof Error?e.message:'Unit creation failed')}finally{setSaving(false)}};
  const saveNews=async()=>{if(!newsForm.title.trim()||!newsForm.content.trim()){alert('News title and content are required.');return}setSaving(true);try{const slug=newsForm.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-6);await post('/api/news',{...newsForm,slug,publishedDate:new Date().toISOString(),isPublished:true,seoTitle:newsForm.title,seoDescription:newsForm.excerpt});setShowNews(false);setNewsForm({title:'',titleAr:'',excerpt:'',excerptAr:'',content:'',contentAr:'',featuredImage:'',author:'Tanmiyat Editorial',category:'Insights'});await onRefresh();}catch(e){alert(e instanceof Error?e.message:'News creation failed')}finally{setSaving(false)}};
  const changeUnitStatus=async(unit:UnitItem,status:UnitItem['status'])=>{try{const r=await fetch(`/api/units/${unit.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({status})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||'Unit status update failed');await onRefresh()}catch(e){alert(e instanceof Error?e.message:'Unit status update failed')}};

  const tabs:[Section,string,React.ElementType,number][]=[['PROJECTS','Master Projects',Building2,projects.length],['UNITS','Inventory Units',Layers3,units.length],['TIMELINE','Heritage Timeline',Clock3,timeline.length],['NEWS','News & Insights',Newspaper,news.length],['USERS','Roles & Access',ShieldCheck,1]];
  return <div className="space-y-6">
    <div><h1 className="font-editorial text-3xl text-[#F5F2EB]">Development & CMS</h1><p className="text-xs text-[#8C867E] mt-1">Central administration for developments, inventory, heritage content, editorial publishing and access policy.</p></div>
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-2">{tabs.map(([id,label,Icon,count])=><button key={id} onClick={()=>setSection(id)} className={`${card} p-3 text-left transition-colors ${section===id?'border-[#B79A62] bg-[#1C1A17]':''}`}><Icon className="w-5 h-5 text-[#B79A62] mb-2"/><div className="text-[10px] uppercase tracking-wider text-[#C8C0B3]">{label}</div><div className="text-xl text-[#F5F2EB] mt-1">{count}</div></button>)}</div>
    {section==='PROJECTS'&&<Panel title="Master Projects" action={<button onClick={()=>setShowProject(true)} className="px-4 py-2 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold"><Plus className="inline w-4 h-4 mr-1"/>New Project</button>}><div className="grid md:grid-cols-2 gap-4">{projects.map(p=><div key={p.id} className={`${card} p-5`}><div className="flex justify-between gap-3"><div><h3 className="text-lg text-[#F5F2EB]">{p.title}</h3><p className="text-[10px] text-[#B79A62] uppercase tracking-wider">{p.category} • {p.status}</p></div><span className="text-[10px] text-[#8C867E]">#{p.order}</span></div><p className="text-xs text-[#8C867E] mt-3">{p.location}</p><p className="text-xs text-[#C8C0B3] mt-2 line-clamp-3">{p.tagline}</p><div className="mt-4 text-[10px] text-[#7A756D]">{(p.units||[]).length} linked units • {p.gallery.length} gallery items • {p.amenities.length} amenities</div></div>)}</div></Panel>}
    {section==='UNITS'&&<Panel title="Inventory Units" action={<button onClick={()=>setShowUnit(true)} className="px-4 py-2 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold"><Plus className="inline w-4 h-4 mr-1"/>Add Unit</button>}><div className={`${card} overflow-x-auto`}><table className="w-full text-xs"><thead className="bg-[#0A0A09] text-[#7A756D]"><tr><th className="p-3 text-left">Unit</th><th className="p-3 text-left">Project</th><th className="p-3 text-left">Type</th><th className="p-3 text-left">Beds</th><th className="p-3 text-left">Area</th><th className="p-3 text-left">Price</th><th className="p-3 text-left">Status</th></tr></thead><tbody className="divide-y divide-[#22201C]">{units.map(u=><tr key={u.id}><td className="p-3 text-[#F5F2EB]">{u.unitNumber}</td><td className="p-3">{projectMap.get(u.projectId)||'Unlinked'}</td><td className="p-3">{u.type}</td><td className="p-3">{u.bedrooms}</td><td className="p-3">{u.areaSqFt.toLocaleString()} sq ft</td><td className="p-3">AED {u.price.toLocaleString()}</td><td className="p-3"><select value={u.status} onChange={e=>void changeUnitStatus(u,e.target.value as UnitItem['status'])} className="bg-[#0A0A09] border border-[#2D2A26] px-2 py-1"><option>AVAILABLE</option><option>RESERVED</option><option>SOLD</option><option>COMING_SOON</option></select></td></tr>)}</tbody></table>{!units.length&&<Empty text="No inventory units are currently indexed."/>}</div></Panel>}
    {section==='TIMELINE'&&<Panel title="Heritage Timeline" action={<button onClick={()=>alert('Timeline editing requires a dedicated write API; existing heritage records are preserved and displayed here.')} className="px-4 py-2 border border-[#B79A62] text-[#D8BE8A] text-xs">Timeline Write API</button>}><div className="space-y-3">{timeline.map(t=><div key={t.id} className={`${card} p-5 flex gap-5`}><div className="text-2xl text-[#B79A62] font-editorial w-20 shrink-0">{t.year}</div><div><h3 className="text-[#F5F2EB]">{t.title}</h3><p className="text-xs text-[#8C867E] mt-1">{t.description}</p></div></div>)}{!timeline.length&&<Empty text="No heritage timeline records found."/>}</div></Panel>}
    {section==='NEWS'&&<Panel title="News & Insights" action={<button onClick={()=>setShowNews(true)} className="px-4 py-2 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold"><Plus className="inline w-4 h-4 mr-1"/>New Article</button>}><div className="grid md:grid-cols-2 gap-4">{news.map(n=><div key={n.id} className={`${card} p-5`}><div className="text-[10px] uppercase tracking-wider text-[#B79A62]">{n.category} • {n.isPublished?'PUBLISHED':'DRAFT'}</div><h3 className="text-lg text-[#F5F2EB] mt-2">{n.title}</h3><p className="text-xs text-[#8C867E] mt-2 line-clamp-3">{n.excerpt}</p><div className="text-[10px] text-[#7A756D] mt-4">{n.author} • {new Date(n.publishedDate).toLocaleDateString()}</div></div>)}{!news.length&&<Empty text="No news articles found."/>}</div></Panel>}
    {section==='USERS'&&<Panel title="Roles & Access"><div className={`${card} p-5`}><div className="flex items-center gap-3"><ShieldCheck className="w-6 h-6 text-[#B79A62]"/><div><div className="text-[#F5F2EB] font-semibold">SUPER_ADMIN</div><div className="text-xs text-[#8C867E]">Current executive account</div></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-5">{['SUPER_ADMIN','ADMIN','SALES_MANAGER','AGENT','MARKETING','CRM_MANAGER','ACCOUNTANT','VIEWER','EDITOR','SALES'].map(role=><div key={role} className="border border-[#25221E] bg-[#0A0A09] px-3 py-2 text-[10px] text-[#C8C0B3]">{role}</div>)}</div><p className="text-xs text-[#8C867E] mt-5">Authentication is currently backed by the configured administrator account and JWT session. The role catalog is aligned with the existing backend authorization model; multi-user credential provisioning is intentionally not fabricated in the CMS.</p></div></Panel>}

    {showProject&&<Modal title="Create Master Project" close={()=>!saving&&setShowProject(false)}><div className="grid md:grid-cols-2 gap-4">{[['Title','title'],['Arabic Title','titleAr'],['Location','location'],['Arabic Location','locationAr'],['Tagline','tagline'],['Arabic Tagline','taglineAr'],['Hero Image URL','heroImage'],['Starting Price AED','startingPrice'],['Completion Date','completionDate']].map(([label,key])=><Field key={key} label={label} value={(projectForm as Record<string,string>)[key]} type={key==='startingPrice'?'number':'text'} onChange={v=>setProjectForm(p=>({...p,[key]:v}))}/>)}<Select label="Category" value={projectForm.category} options={['RESIDENTIAL','COMMERCIAL','MIXED_USE','MASTER_COMMUNITY']} onChange={v=>setProjectForm(p=>({...p,category:v}))}/><Select label="Status" value={projectForm.status} options={['COMPLETED','ONGOING','UPCOMING']} onChange={v=>setProjectForm(p=>({...p,status:v}))}/></div><TextArea label="Overview" value={projectForm.overview} onChange={v=>setProjectForm(p=>({...p,overview:v}))}/><TextArea label="Architecture" value={projectForm.architecture} onChange={v=>setProjectForm(p=>({...p,architecture:v}))}/><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setShowProject(false)} className="px-4 py-2 border border-[#332F28]">Cancel</button><button onClick={()=>void saveProject()} disabled={saving} className="px-5 py-2 bg-[#B79A62] text-[#0A0A09] font-semibold"><Save className="inline w-4 h-4 mr-1"/>{saving?'Saving...':'Create Project'}</button></div></Modal>}
    {showUnit&&<Modal title="Add Inventory Unit" close={()=>!saving&&setShowUnit(false)}><div className="grid md:grid-cols-2 gap-4"><Select label="Project" value={unitForm.projectId} options={projects.map(p=>p.id)} labels={projects.map(p=>p.title)} onChange={v=>setUnitForm(p=>({...p,projectId:v}))}/><Field label="Unit Number" value={unitForm.unitNumber} onChange={v=>setUnitForm(p=>({...p,unitNumber:v}))}/><Field label="Type" value={unitForm.type} onChange={v=>setUnitForm(p=>({...p,type:v}))}/><Field label="Bedrooms" value={unitForm.bedrooms} type="number" onChange={v=>setUnitForm(p=>({...p,bedrooms:v}))}/><Field label="Bathrooms" value={unitForm.bathrooms} type="number" onChange={v=>setUnitForm(p=>({...p,bathrooms:v}))}/><Field label="Area Sq Ft" value={unitForm.areaSqFt} type="number" onChange={v=>setUnitForm(p=>({...p,areaSqFt:v}))}/><Field label="Floor" value={unitForm.floor} type="number" onChange={v=>setUnitForm(p=>({...p,floor:v}))}/><Field label="Price AED" value={unitForm.price} type="number" onChange={v=>setUnitForm(p=>({...p,price:v}))}/><Select label="Status" value={unitForm.status} options={['AVAILABLE','RESERVED','SOLD','COMING_SOON']} onChange={v=>setUnitForm(p=>({...p,status:v}))}/></div><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setShowUnit(false)} className="px-4 py-2 border border-[#332F28]">Cancel</button><button onClick={()=>void saveUnit()} disabled={saving} className="px-5 py-2 bg-[#B79A62] text-[#0A0A09] font-semibold"><Save className="inline w-4 h-4 mr-1"/>{saving?'Saving...':'Create Unit'}</button></div></Modal>}
    {showNews&&<Modal title="Publish News & Insight" close={()=>!saving&&setShowNews(false)}><div className="grid md:grid-cols-2 gap-4"><Field label="Title" value={newsForm.title} onChange={v=>setNewsForm(p=>({...p,title:v}))}/><Field label="Arabic Title" value={newsForm.titleAr} onChange={v=>setNewsForm(p=>({...p,titleAr:v}))}/><Field label="Featured Image URL" value={newsForm.featuredImage} onChange={v=>setNewsForm(p=>({...p,featuredImage:v}))}/><Field label="Category" value={newsForm.category} onChange={v=>setNewsForm(p=>({...p,category:v}))}/><Field label="Author" value={newsForm.author} onChange={v=>setNewsForm(p=>({...p,author:v}))}/></div><TextArea label="Excerpt" value={newsForm.excerpt} onChange={v=>setNewsForm(p=>({...p,excerpt:v}))}/><TextArea label="Content" value={newsForm.content} onChange={v=>setNewsForm(p=>({...p,content:v}))}/><TextArea label="Arabic Content" value={newsForm.contentAr} onChange={v=>setNewsForm(p=>({...p,contentAr:v}))}/><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setShowNews(false)} className="px-4 py-2 border border-[#332F28]">Cancel</button><button onClick={()=>void saveNews()} disabled={saving} className="px-5 py-2 bg-[#B79A62] text-[#0A0A09] font-semibold"><Save className="inline w-4 h-4 mr-1"/>{saving?'Publishing...':'Publish Article'}</button></div></Modal>}
  </div>;
};

const Panel=({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode})=><section className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 className="font-editorial text-2xl text-[#F5F2EB]">{title}</h2>{action}</div>{children}</section>;
const Empty=({text}:{text:string})=><div className="p-8 text-center text-xs text-[#7A756D]">{text}</div>;
const Field=({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string})=><label className="block"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><input className={input} type={type} value={value||''} onChange={e=>onChange(e.target.value)}/></label>;
const TextArea=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className="block mt-4"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><textarea rows={5} className={input} value={value||''} onChange={e=>onChange(e.target.value)}/></label>;
const Select=({label,value,options,onChange,labels}:{label:string;value:string;options:string[];onChange:(v:string)=>void;labels?:string[]})=><label className="block"><span className="block text-[10px] uppercase tracking-wider text-[#8C867E] mb-1">{label}</span><select className={input} value={value} onChange={e=>onChange(e.target.value)}><option value="">Select</option>{options.map((o,i)=><option key={o} value={o}>{labels?.[i]||o}</option>)}</select></label>;
const Modal=({title,close,children}:{title:string;close:()=>void;children:React.ReactNode})=><div className="fixed inset-0 z-[80] bg-black/80 flex items-center justify-center p-4"><div className="w-full max-w-4xl max-h-[92vh] overflow-y-auto bg-[#171715] border border-[#25221E] p-6 sm:p-8"><div className="flex justify-between items-center mb-6"><h3 className="font-editorial text-2xl text-[#F5F2EB]">{title}</h3><button onClick={close}><X className="w-5 h-5 text-[#8C867E]"/></button></div>{children}</div></div>;
