'use client';

import React, { useMemo, useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { PropertyItem, AgentItem } from '@/types';
import { Building, Plus, Search, Trash2, X, Eye, EyeOff, Upload, ImagePlus, Video, UserRound, Phone, Mail, MessageCircle } from 'lucide-react';
import { AgentsManager } from '@/components/admin/crm/AgentsManager';

type Props = { initialProperties: PropertyItem[]; agents: AgentItem[] };
const DUBAI_LOCATIONS = ['Downtown Dubai','Business Bay','DIFC','Dubai Design District (D3)','Dubai International Financial Centre','Dubai Creek Harbour','Dubai Festival City','Dubai Hills Estate','Dubai Marina','Jumeirah Beach Residence (JBR)','Palm Jumeirah','Bluewaters Island','City Walk','Jumeirah 1','Jumeirah 2','Jumeirah 3','Jumeirah Village Circle (JVC)','Jumeirah Village Triangle (JVT)','Al Barsha 1','Al Barsha 2','Al Barsha 3','Al Barsha South','Barsha Heights (TECOM)','Al Sufouh 1','Al Sufouh 2','Umm Suqeim 1','Umm Suqeim 2','Umm Suqeim 3','Al Wasl','Al Quoz','Meydan','Mohammed Bin Rashid City (MBR City)','Nad Al Sheba','Emirates Hills','The Lakes','The Meadows','The Springs','Jumeirah Islands','Dubai Sports City','Motor City','Arabian Ranches','Arabian Ranches 2','Dubai Land Residence Complex (DLRC)','Dubailand','Damac Hills','Damac Hills 2','Town Square Dubai','The Valley','Dubai South','Expo City Dubai','Dubai Investment Park (DIP)','Jebel Ali','Discovery Gardens','The Gardens','Dubai Production City','Dubai Studio City','Dubai Science Park','Dubai Silicon Oasis (DSO)','Dubai Academic City','International City','Al Warsan','Al Warqa 1','Al Warqa 2','Al Warqa 3','Al Warqa 4','Mirdif','Nad Al Hamar','Al Garhoud','Deira','Bur Dubai','Al Jaddaf','Ras Al Khor','Dubai Healthcare City','Dubai Maritime City','Dubai Islands','Dubai Water Canal','Dubai Harbour','Dubai Internet City','Dubai Media City','Dubai Knowledge Park','Jumeirah Golf Estates'];
const PROPERTY_TYPES = ['Penthouse','Villa','Apartment','Townhouse','Duplex','Mansion','Studio','Office','Retail'];
const FALLBACK_IMAGE = 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80';

export const PropertiesManager: React.FC<Props> = ({ initialProperties, agents: initialAgents }) => {
  const [properties, setProperties] = useState<PropertyItem[]>(initialProperties);
  const [agents, setAgents] = useState<AgentItem[]>(initialAgents);
  const [search, setSearch] = useState(''); const [purposeFilter, setPurposeFilter] = useState('ALL'); const [communityFilter, setCommunityFilter] = useState('ALL');
  const [showAddModal, setShowAddModal] = useState(false);
  const [title, setTitle] = useState(''); const [purpose, setPurpose] = useState<'FOR_SALE'|'FOR_RENT'>('FOR_SALE'); const [type, setType] = useState('Penthouse');
  const [community, setCommunity] = useState('Business Bay'); const [subCommunity, setSubCommunity] = useState(''); const [address, setAddress] = useState(''); const [price, setPrice] = useState(''); const [beds, setBeds] = useState('3'); const [baths, setBaths] = useState('4'); const [area, setArea] = useState(''); const [parking, setParking] = useState('2'); const [furnished, setFurnished] = useState<'FURNISHED'|'SEMI_FURNISHED'|'UNFURNISHED'>('FURNISHED'); const [agentId, setAgentId] = useState(''); const [permit, setPermit] = useState(''); const [images, setImages] = useState<string[]>([]); const [videos, setVideos] = useState<string[]>([]); const [imageUrl, setImageUrl] = useState(''); const [videoUrl, setVideoUrl] = useState(''); const [description, setDescription] = useState(''); const [uploading, setUploading] = useState(false); const [saving, setSaving] = useState(false);
  const imageRef = useRef<HTMLInputElement>(null); const videoRef = useRef<HTMLInputElement>(null);
  const selectedAgent = useMemo(() => agents.find((a) => a.id === agentId), [agents, agentId]);
  const filtered = properties.filter((p) => { if (purposeFilter !== 'ALL' && p.purpose !== purposeFilter) return false; if (communityFilter !== 'ALL' && p.community !== communityFilter) return false; if (search.trim() && ![p.title,p.referenceNumber,p.community,p.address,p.agent?.name || ''].some((v) => v.toLowerCase().includes(search.toLowerCase()))) return false; return true; });

  const uploadFiles = async (files: FileList | File[]) => { setUploading(true); try { for (const file of Array.from(files)) { const form = new FormData(); form.append('file', file); const res = await fetch('/api/uploads',{method:'POST',body:form}); const json = await res.json().catch(()=>({})); if(!res.ok || !json.success || !json.data?.url) throw new Error(json.error || `Upload failed: ${file.name}`); if(file.type.startsWith('video/')) setVideos((v)=>[...v,json.data.url]); else setImages((v)=>[...v,json.data.url]); } } catch(e){ alert(e instanceof Error ? e.message : 'Media upload failed.'); } finally { setUploading(false); } };
  const reset = () => { setTitle('');setPurpose('FOR_SALE');setType('Penthouse');setCommunity('Business Bay');setSubCommunity('');setAddress('');setPrice('');setBeds('3');setBaths('4');setArea('');setParking('2');setFurnished('FURNISHED');setAgentId('');setPermit('');setImages([]);setVideos([]);setImageUrl('');setVideoUrl('');setDescription(''); };
  const createProperty = async (e: React.FormEvent) => { e.preventDefault(); if(!title.trim()||!price||!area||!agentId){ alert('Please select a listing agent.'); return; } setSaving(true); try { const numericPrice=Number(price.replace(/[^0-9.]/g,'')); const numericArea=Number(area.replace(/[^0-9.]/g,'')); const gallery=images.length?images:[FALLBACK_IMAGE]; const slug=`${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${Date.now().toString().slice(-5)}`; const selected=agents.find((a)=>a.id===agentId); const res=await fetch('/api/properties',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({referenceNumber:`TAN-DXB-${Math.floor(1000+Math.random()*9000)}`,title:title.trim(),slug,purpose,propertyType:type,community,subCommunity:subCommunity||community,address:address.trim()||`${subCommunity||community}, Dubai, UAE`,price:numericPrice,currency:'AED',rentalPeriod:purpose==='FOR_RENT'?'YEARLY':undefined,bedrooms:Number(beds),bathrooms:Number(baths),parkingSpaces:Number(parking),area:numericArea,furnished,developer:'Tanmiyat Real Estate Development LLC',project:subCommunity||community,agentId,agent:selected,reraBrokerId:selected?.reraBrokerId,brokerORN:selected?.reraBrokerId,agentBRN:selected?.brn,advertisingPermitNumber:permit||`DLD-PERMIT-2026-${Math.floor(1000+Math.random()*9000)}`,featured:false,exclusive:false,verified:true,verificationStatus:'VERIFIED',workflowStatus:'PUBLISHED',status:'AVAILABLE',heroImage:gallery[0],featuredImage:gallery[0],images:gallery,videoUrl:videos[0],videoUrls:videos,description:description.trim()||`${title.trim()} located in prime ${community}, Dubai.`,amenities:['Concierge Service','Swimming Pool','Private Parking','Smart Home System']})}); const json=await res.json().catch(()=>({})); if(!res.ok||!json.success) throw new Error(json.error||'Property creation failed.'); setProperties((p)=>json.data?[json.data,...p]:p);setShowAddModal(false);reset(); } catch(e){alert(e instanceof Error?e.message:'Property creation failed.');} finally{setSaving(false);} };
  const togglePublish=async(id:string,status:string)=>{const next=status==='PUBLISHED'?'DRAFT':'PUBLISHED';const r=await fetch(`/api/properties/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflowStatus:next})});if(r.ok)setProperties((p)=>p.map(x=>x.id===id?{...x,workflowStatus:next as PropertyItem['workflowStatus']}:x));};
  const toggleVerify=async(id:string,verified:boolean)=>{const next=!verified;const r=await fetch(`/api/properties/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({verified:next,verificationStatus:next?'VERIFIED':'PENDING_VERIFICATION'})});if(r.ok)setProperties((p)=>p.map(x=>x.id===id?{...x,verified:next,verificationStatus:next?'VERIFIED':'PENDING_VERIFICATION'}:x));};
  const deleteProperty=async(id:string)=>{if(!confirm('Are you sure you want to permanently delete this property listing?'))return;const r=await fetch(`/api/properties/${id}`,{method:'DELETE'});if(r.ok)setProperties((p)=>p.filter(x=>x.id!==id));};

  return <div className="space-y-8">
    <AgentsManager agents={agents} onAgentsChange={setAgents} />
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-3"><h1 className="font-editorial text-3xl text-[#F5F2EB]">Marketplace Properties & Listings</h1><span className="px-2.5 py-0.5 bg-[#B79A62]/10 border border-[#B79A62]/30 text-[#B79A62] text-xs font-semibold">{properties.length} Assets</span></div><p className="text-xs text-[#8C867E]">Assign every sale or rental property to a named licensed advisor.</p></div><button onClick={()=>setShowAddModal(true)} className="px-4 py-2.5 bg-[#B79A62] text-[#0A0A09] text-xs font-semibold uppercase tracking-wider flex items-center gap-1.5"><Plus className="w-4 h-4"/>New Property Listing</button></div>
    <div className="bg-[#171715] border border-[#25221E] p-4 flex flex-col sm:flex-row gap-3 text-xs"><div className="relative w-full sm:w-72"><Search className="w-4 h-4 text-[#8C867E] absolute left-3 top-1/2 -translate-y-1/2"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search title, reference, location, agent..." className="w-full bg-[#0A0A09] border border-[#25221E] pl-9 pr-3 py-2 text-[#F5F2EB] outline-none"/></div><select value={purposeFilter} onChange={(e)=>setPurposeFilter(e.target.value)} className="bg-[#0A0A09] border border-[#25221E] px-3 py-2 text-[#C8C0B3]"><option value="ALL">All Purposes</option><option value="FOR_SALE">For Sale</option><option value="FOR_RENT">For Rent</option></select><select value={communityFilter} onChange={(e)=>setCommunityFilter(e.target.value)} className="bg-[#0A0A09] border border-[#25221E] px-3 py-2 text-[#C8C0B3]"><option value="ALL">All Locations</option>{DUBAI_LOCATIONS.map((x)=><option key={x}>{x}</option>)}</select></div>
    <div className="bg-[#171715] border border-[#25221E] overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-[#0A0A09] text-[#7A756D] uppercase tracking-wider"><tr><th className="py-3 px-4">Residence</th><th className="py-3 px-4">Location</th><th className="py-3 px-4">Assigned Agent</th><th className="py-3 px-4">Purpose</th><th className="py-3 px-4">Price</th><th className="py-3 px-4">Status</th><th className="py-3 px-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#22201C]">{filtered.map((p)=><tr key={p.id} className="hover:bg-[#1E1C18]"><td className="py-3 px-4"><div className="flex items-center gap-3"><div className="relative w-12 h-10 overflow-hidden bg-[#0A0A09]"><Image src={p.featuredImage||p.heroImage} alt={p.title} fill className="object-cover" sizes="48px" referrerPolicy="no-referrer"/></div><div><span className="text-[#F5F2EB] block">{p.title}</span><span className="text-[10px] text-[#7A756D] font-mono">{p.referenceNumber}</span></div></div></td><td className="py-3 px-4"><div>{p.community}</div><div className="text-[10px] text-[#7A756D]">{p.subCommunity||p.address}</div></td><td className="py-3 px-4"><div className="text-[#F5F2EB] font-medium">{p.agent?.name||agents.find((a)=>a.id===p.agentId)?.name||'Unassigned'}</div>{(p.agent?.brn||agents.find((a)=>a.id===p.agentId)?.brn)&&<div className="text-[10px] text-[#7A756D]">BRN {p.agent?.brn||agents.find((a)=>a.id===p.agentId)?.brn}</div>}</td><td className="py-3 px-4"><span className="px-2 py-0.5 bg-[#B79A62] text-[#0A0A09] text-[9px] font-bold uppercase">{p.purpose==='FOR_RENT'?'Rent':'Sale'}</span></td><td className="py-3 px-4 font-editorial text-sm text-[#F5F2EB]">AED {p.price.toLocaleString()}{p.purpose==='FOR_RENT'&&<span className="text-[10px] text-[#7A756D] font-sans"> /yr</span>}</td><td className="py-3 px-4"><span className="text-[10px] uppercase">{p.workflowStatus||'PUBLISHED'}</span></td><td className="py-3 px-4 text-right whitespace-nowrap"><button onClick={()=>togglePublish(p.id,p.workflowStatus||'PUBLISHED')} className="p-1 text-[#8C867E]" title="Publish/Draft">{p.workflowStatus==='PUBLISHED'?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button><Link href={`/properties/${p.slug}`} target="_blank" className="p-1 text-[#8C867E] inline-block" title="View"><Building className="w-4 h-4"/></Link><button onClick={()=>deleteProperty(p.id)} className="p-1 text-[#8C867E] hover:text-red-400" title="Delete"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div>

    {showAddModal&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85"><div className="relative w-full max-w-4xl bg-[#171715] border border-[#25221E] p-6 max-h-[92vh] overflow-y-auto"><div className="flex justify-between items-center pb-4 border-b border-[#25221E] mb-5"><div><h2 className="font-editorial text-2xl text-[#F5F2EB]">Create Property Listing</h2><p className="text-[11px] text-[#8C867E]">Choose the responsible agent so clients can contact the correct advisor.</p></div><button onClick={()=>setShowAddModal(false)}><X className="w-5 h-5 text-[#8C867E]"/></button></div><form onSubmit={createProperty} className="space-y-5 text-xs">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Property Title *" value={title} setValue={setTitle} required/><Field label="Property Type" value={type} setValue={setType} select={PROPERTY_TYPES}/></div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Purpose" value={purpose} setValue={(v)=>setPurpose(v as 'FOR_SALE'|'FOR_RENT')} select={['FOR_SALE','FOR_RENT']}/><Field label="Community / Location" value={community} setValue={setCommunity} select={DUBAI_LOCATIONS}/><Field label="Building / Sub-community" value={subCommunity} setValue={setSubCommunity}/></div>
      <Field label="Full Address" value={address} setValue={setAddress}/><div className="grid grid-cols-2 md:grid-cols-5 gap-4"><Field label="Price (AED) *" value={price} setValue={setPrice} type="number" required/><Field label="Area Sq.Ft *" value={area} setValue={setArea} type="number" required/><Field label="Bedrooms" value={beds} setValue={setBeds} type="number"/><Field label="Bathrooms" value={baths} setValue={setBaths} type="number"/><Field label="Parking" value={parking} setValue={setParking} type="number"/></div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Furnished" value={furnished} setValue={(v)=>setFurnished(v as typeof furnished)} select={['FURNISHED','SEMI_FURNISHED','UNFURNISHED']}/><Field label="DLD / Trakheesi Permit" value={permit} setValue={setPermit}/></div>
      <div className="bg-[#0A0A09] border border-[#25221E] p-4 space-y-3"><div className="flex items-center gap-2 text-[#B79A62] font-semibold uppercase tracking-wider"><UserRound className="w-4 h-4"/>Listing Agent *</div><select required value={agentId} onChange={(e)=>setAgentId(e.target.value)} className="field-input"><option value="">Select Agent / Advisor</option>{agents.filter((a)=>a.status==='ACTIVE').map((a)=><option key={a.id} value={a.id}>{a.name} • BRN {a.brn||'N/A'}</option>)}</select>{selectedAgent&&<div className="flex flex-wrap items-center gap-4 p-3 border border-[#25221E]"><div className="flex items-center gap-2">{selectedAgent.photo?<div className="relative w-12 h-12 rounded-full overflow-hidden"><Image src={selectedAgent.photo} alt={selectedAgent.name} fill className="object-cover" sizes="48px"/></div>:<UserRound className="w-10 h-10 text-[#B79A62]"/>}<div><div className="text-[#F5F2EB] font-semibold">{selectedAgent.name}</div><div className="text-[10px] text-[#B79A62]">{selectedAgent.designation} • BRN {selectedAgent.brn}</div></div></div><span className="text-[#A8A196]"><Phone className="w-3 h-3 inline mr-1"/>{selectedAgent.phone}</span><span className="text-[#A8A196]"><MessageCircle className="w-3 h-3 inline mr-1"/>{selectedAgent.whatsApp}</span><span className="text-[#A8A196]"><Mail className="w-3 h-3 inline mr-1"/>{selectedAgent.email}</span></div>}</div>
      <MediaSection title="Property Images" icon={<ImagePlus className="w-4 h-4"/>} accept="image/*" inputRef={imageRef} uploading={uploading} onFiles={(f)=>void uploadFiles(f)} urls={images} setUrls={setImages} text="Upload Images — select as many as needed" url={imageUrl} setUrl={setImageUrl}/>
      <MediaSection title="Property Videos" icon={<Video className="w-4 h-4"/>} accept="video/*" inputRef={videoRef} uploading={uploading} onFiles={(f)=>void uploadFiles(f)} urls={videos} setUrls={setVideos} text="Upload Videos — select as many as needed" url={videoUrl} setUrl={setVideoUrl}/>
      <Field label="Description" value={description} setValue={setDescription} textarea/>
      <button type="submit" disabled={saving||uploading} className="w-full py-3.5 bg-[#B79A62] text-[#0A0A09] font-semibold uppercase tracking-wider disabled:opacity-50">{saving?'Publishing...':'Publish Property to Live Marketplace'}</button>
    </form></div></div>}
    <style jsx>{`.field-input{width:100%;background:#0A0A09;border:1px solid #25221E;padding:.6rem .75rem;color:#F5F2EB;outline:none}.field-input:focus{border-color:#B79A62}`}</style>
  </div>;
};

const Field = ({label,value,setValue,type='text',required=false,select,textarea}:{label:string;value:string;setValue:(v:string)=>void;type?:string;required?:boolean;select?:string[];textarea?:boolean}) => <div><label className="block mb-1 text-[10px] uppercase tracking-wider text-[#8C867E]">{label}</label>{textarea?<textarea rows={4} value={value} onChange={(e)=>setValue(e.target.value)} className="field-input resize-none"/>:select?<select required={required} value={value} onChange={(e)=>setValue(e.target.value)} className="field-input">{select.map((x)=><option key={x} value={x}>{x}</option>)}</select>:<input required={required} type={type} value={value} onChange={(e)=>setValue(e.target.value)} className="field-input"/>}</div>;

const MediaSection = ({title,icon,accept,inputRef,uploading,onFiles,urls,setUrls,text,url,setUrl}:{title:string;icon:React.ReactNode;accept:string;inputRef:React.RefObject<HTMLInputElement | null>;uploading:boolean;onFiles:(files:FileList)=>void;urls:string[];setUrls:React.Dispatch<React.SetStateAction<string[]>>;text:string;url:string;setUrl:(v:string)=>void}) => <div className="bg-[#0A0A09] border border-[#25221E] p-4 space-y-3"><div className="flex items-center justify-between text-[#B79A62] font-semibold uppercase tracking-wider"> <div className="flex items-center gap-2">{icon}{title}</div><span className="text-[10px] text-[#8C867E]">{urls.length} selected</span></div><input ref={inputRef} type="file" accept={accept} multiple hidden onChange={(e)=>{if(e.target.files)onFiles(e.target.files);e.currentTarget.value='';}}/><button type="button" disabled={uploading} onClick={()=>inputRef.current?.click()} className="w-full py-3 border border-dashed border-[#B79A62]/50 text-[#D8BE8A] flex items-center justify-center gap-2"><Upload className="w-4 h-4"/>{uploading?'Uploading...':text}</button><div className="flex gap-2"><input value={url} onChange={(e)=>setUrl(e.target.value)} placeholder={`Or paste a ${title.toLowerCase()} URL`} className="field-input flex-1"/><button type="button" onClick={()=>{if(url.trim()){setUrls((u)=>[...u,url.trim()]);setUrl('');}}} className="px-4 border border-[#25221E] text-[#C8C0B3]">Add URL</button></div>{urls.length>0&&<div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-2">{urls.map((u,i)=><div key={`${u}-${i}`} className="relative border border-[#25221E] p-2 min-w-0"><span className="text-[9px] text-[#A8A196] block truncate">{i+1}. {u}</span><button type="button" onClick={()=>setUrls((v)=>v.filter((_,n)=>n!==i))} className="absolute top-1 right-1 text-red-400"><X className="w-3 h-3"/></button></div>)}</div>}</div>;
